packages:
  - packages/**
  - examples

minimumReleaseAge: 1440 # 1 day

catalogs:
  blockchain:
    '@aptos-labs/script-composer-pack': 0.2.1
    '@aptos-labs/ts-sdk': 5.2.1
    '@hyperionxyz/sdk': 0.0.25
    '@thalalabs/surf': 1.8.1
  dev:
    '@antfu/ni': 28.2.0
    bumpp: ^10.4.0
    husky: 9.1.7
    lint-staged: 16.2.7
    rimraf: 6.1.2
    simple-git-hooks: 2.13.1
    tsdown: 0.20.0-beta.3
    tsx: 4.21.0
    typescript: ^5.9.3
    vitest: 4.0.17
    changelogen: 0.6.2
  lint:
    '@antfu/eslint-config': 7.0.1
    '@commitlint/cli': 20.3.1
    '@commitlint/config-conventional': 20.3.1
    eslint: 9.39.2
    eslint-plugin-format: 1.3.1
    eslint-plugin-oxlint: 1.40.0
    oxlint: 1.40.0
    oxlint-tsgolint: 0.11.1
  types:
    '@types/node': 25.0.9
  utils:
    '@itsmnthn/big-utils': 2.0.3

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
