packages:
  - packages/**
  - examples

minimumReleaseAge: 1440 # 1 day

catalogs:
  blockchain:
    '@aptos-labs/script-composer-pack': 0.2.0
    '@aptos-labs/ts-sdk': 5.1.1
    '@hyperionxyz/sdk': 0.0.22
    '@thalalabs/surf': 1.8.1
  dev:
    '@antfu/ni': 26.1.0
    bumpp: 10.3.1
    husky: 9.1.7
    lint-staged: 16.2.4
    rimraf: 6.0.1
    simple-git-hooks: 2.13.1
    tsdown: 0.15.7
    tsx: 4.20.6
    typescript: ^5.9.3
    vitest: 3.2.4
    changelogen: 0.6.2
  lint:
    '@antfu/eslint-config': 6.0.0
    '@commitlint/cli': 20.1.0
    '@commitlint/config-conventional': 20.0.0
    eslint: 9.37.0
    eslint-plugin-format: 1.0.2
    eslint-plugin-oxlint: 1.23.0
    oxlint: 1.23.0
    oxlint-tsgolint: 0.2.0
  types:
    '@types/node': 24.8.0
  utils:
    '@itsmnthn/big-utils': 2.0.3

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
