packages:
  - packages/**
  - examples

minimumReleaseAge: 1440 # 1 day

catalogs:
  blockchain:
    '@aptos-labs/script-composer-pack': 0.2.0
    '@aptos-labs/ts-sdk': 5.2.0
    '@hyperionxyz/sdk': 0.0.25
    '@thalalabs/surf': 1.8.1
  dev:
    '@antfu/ni': 28.0.0
    bumpp: 10.3.2
    husky: 9.1.7
    lint-staged: 16.2.7
    rimraf: 6.1.2
    simple-git-hooks: 2.13.1
    tsdown: 0.16.6
    tsx: 4.21.0
    typescript: ^5.9.3
    vitest: 3.2.4
    changelogen: 0.6.2
  lint:
    '@antfu/eslint-config': 6.7.3
    '@commitlint/cli': 20.2.0
    '@commitlint/config-conventional': 20.2.0
    eslint: 9.39.2
    eslint-plugin-format: 1.1.0
    eslint-plugin-oxlint: 1.35.0
    oxlint: 1.35.0
    oxlint-tsgolint: 0.10.0
  types:
    '@types/node': 24.10.1
  utils:
    '@itsmnthn/big-utils': 2.0.3

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
