// This file is auto-generated by the generate-abis.ts script
export const composerUtils_fe_abi = {
  "address": "0x0",
  "name": "fe",
  "friends": [],
  "exposed_functions": [
    {
      "name": "any_singleton",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "0x1::copyable_any::Any"
      ],
      "return": [
        "vector<0x1::copyable_any::Any>"
      ]
    }
  ],
  "structs": []
} as const;
