// This file is auto-generated by the generate-abis.ts script
export const generic_copyable_any_abi = {
  "address": "0x0",
  "name": "copyable_any",
  "friends": [],
  "exposed_functions": [
    {
      "name": "type_name",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&0x1::copyable_any::Any"
      ],
      "return": [
        "&0x1::string::String"
      ]
    },
    {
      "name": "pack",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": [
            "copy",
            "drop",
            "store"
          ]
        }
      ],
      "params": [
        "T0"
      ],
      "return": [
        "0x1::copyable_any::Any"
      ]
    },
    {
      "name": "unpack",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "0x1::copyable_any::Any"
      ],
      "return": [
        "T0"
      ]
    }
  ],
  "structs": [
    {
      "name": "Any",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "type_name",
          "type": "0x1::string::String"
        },
        {
          "name": "data",
          "type": "vector<u8>"
        }
      ]
    }
  ]
} as const;
