// This file is auto-generated by the generate-abis.ts script
export const generic_primary_fungible_store_abi = {
  "address": "0x0",
  "name": "primary_fungible_store",
  "friends": [],
  "exposed_functions": [
    {
      "name": "burn",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&0x1::fungible_asset::BurnRef",
        "address",
        "u64"
      ],
      "return": []
    },
    {
      "name": "grant_permission",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": [
            "key"
          ]
        }
      ],
      "params": [
        "&signer",
        "&signer",
        "0x1::object::Object<T0>",
        "u64"
      ],
      "return": []
    },
    {
      "name": "transfer",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": [
            "key"
          ]
        }
      ],
      "params": [
        "&signer",
        "0x1::object::Object<T0>",
        "address",
        "u64"
      ],
      "return": []
    },
    {
      "name": "transfer_with_ref",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&0x1::fungible_asset::TransferRef",
        "address",
        "address",
        "u64"
      ],
      "return": []
    },
    {
      "name": "balance",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [
        {
          "constraints": [
            "key"
          ]
        }
      ],
      "params": [
        "address",
        "0x1::object::Object<T0>"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "deposit",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "address",
        "0x1::fungible_asset::FungibleAsset"
      ],
      "return": []
    },
    {
      "name": "deposit_with_ref",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&0x1::fungible_asset::TransferRef",
        "address",
        "0x1::fungible_asset::FungibleAsset"
      ],
      "return": []
    },
    {
      "name": "is_balance_at_least",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [
        {
          "constraints": [
            "key"
          ]
        }
      ],
      "params": [
        "address",
        "0x1::object::Object<T0>",
        "u64"
      ],
      "return": [
        "bool"
      ]
    },
    {
      "name": "is_frozen",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [
        {
          "constraints": [
            "key"
          ]
        }
      ],
      "params": [
        "address",
        "0x1::object::Object<T0>"
      ],
      "return": [
        "bool"
      ]
    },
    {
      "name": "mint",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&0x1::fungible_asset::MintRef",
        "address",
        "u64"
      ],
      "return": []
    },
    {
      "name": "set_frozen_flag",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&0x1::fungible_asset::TransferRef",
        "address",
        "bool"
      ],
      "return": []
    },
    {
      "name": "withdraw",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": [
            "key"
          ]
        }
      ],
      "params": [
        "&signer",
        "0x1::object::Object<T0>",
        "u64"
      ],
      "return": [
        "0x1::fungible_asset::FungibleAsset"
      ]
    },
    {
      "name": "withdraw_with_ref",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&0x1::fungible_asset::TransferRef",
        "address",
        "u64"
      ],
      "return": [
        "0x1::fungible_asset::FungibleAsset"
      ]
    },
    {
      "name": "transfer_assert_minimum_deposit",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": [
            "key"
          ]
        }
      ],
      "params": [
        "&signer",
        "0x1::object::Object<T0>",
        "address",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "create_primary_store",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": [
            "key"
          ]
        }
      ],
      "params": [
        "address",
        "0x1::object::Object<T0>"
      ],
      "return": [
        "0x1::object::Object<0x1::fungible_asset::FungibleStore>"
      ]
    },
    {
      "name": "create_primary_store_enabled_fungible_asset",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&0x1::object::ConstructorRef",
        "0x1::option::Option<u128>",
        "0x1::string::String",
        "0x1::string::String",
        "u8",
        "0x1::string::String",
        "0x1::string::String"
      ],
      "return": []
    },
    {
      "name": "deposit_with_signer",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::fungible_asset::FungibleAsset"
      ],
      "return": []
    },
    {
      "name": "ensure_primary_store_exists",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": [
            "key"
          ]
        }
      ],
      "params": [
        "address",
        "0x1::object::Object<T0>"
      ],
      "return": [
        "0x1::object::Object<0x1::fungible_asset::FungibleStore>"
      ]
    },
    {
      "name": "grant_apt_permission",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "&signer",
        "u64"
      ],
      "return": []
    },
    {
      "name": "primary_store",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [
        {
          "constraints": [
            "key"
          ]
        }
      ],
      "params": [
        "address",
        "0x1::object::Object<T0>"
      ],
      "return": [
        "0x1::object::Object<0x1::fungible_asset::FungibleStore>"
      ]
    },
    {
      "name": "primary_store_address",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [
        {
          "constraints": [
            "key"
          ]
        }
      ],
      "params": [
        "address",
        "0x1::object::Object<T0>"
      ],
      "return": [
        "address"
      ]
    },
    {
      "name": "primary_store_exists",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [
        {
          "constraints": [
            "key"
          ]
        }
      ],
      "params": [
        "address",
        "0x1::object::Object<T0>"
      ],
      "return": [
        "bool"
      ]
    }
  ],
  "structs": [
    {
      "name": "DeriveRefPod",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "key"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "metadata_derive_ref",
          "type": "0x1::object::DeriveRef"
        }
      ]
    }
  ]
} as const;
