// This file is auto-generated by the generate-abis.ts script
export const goblin_vaults_abi = {
  "address": "0x0",
  "name": "vaults",
  "friends": [],
  "exposed_functions": [
    {
      "name": "close_position",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>"
      ],
      "return": []
    },
    {
      "name": "close_swap_rebalance",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>",
        "address",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "u64",
        "u32",
        "u32",
        "u64",
        "u64",
        "u64",
        "u64",
        "bool"
      ],
      "return": []
    },
    {
      "name": "close_swap_rebalance_auto",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>",
        "u32",
        "u32"
      ],
      "return": []
    },
    {
      "name": "compound",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>",
        "u64",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "compound_auto",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>"
      ],
      "return": []
    },
    {
      "name": "create_vault",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8",
        "u32",
        "u32",
        "u64",
        "u64",
        "u64",
        "u64",
        "vector<address>",
        "vector<u64>",
        "address",
        "0x1::string::String"
      ],
      "return": []
    },
    {
      "name": "deposit_with_pair",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>",
        "u64",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "deposit_with_pair_both_coin",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        },
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>",
        "u64",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "deposit_with_pair_coin",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "deposit_with_single",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>",
        "bool",
        "address",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "deposit_with_single_coin",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>",
        "bool",
        "address",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "does_vault_paused",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>"
      ],
      "return": [
        "bool"
      ]
    },
    {
      "name": "get_cap",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>"
      ],
      "return": [
        "u64",
        "u64"
      ]
    },
    {
      "name": "get_liquidity_by_share",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>",
        "u64"
      ],
      "return": [
        "u128"
      ]
    },
    {
      "name": "get_tick_spacing",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "u8"
      ],
      "return": [
        "u32"
      ]
    },
    {
      "name": "get_token_amount_by_address",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>",
        "address"
      ],
      "return": [
        "u64",
        "u64"
      ]
    },
    {
      "name": "get_token_amount_by_share",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>",
        "u64"
      ],
      "return": [
        "u64",
        "u64"
      ]
    },
    {
      "name": "get_vault_position_and_pool",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>"
      ],
      "return": [
        "address",
        "address"
      ]
    },
    {
      "name": "get_vault_token_ab",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>"
      ],
      "return": [
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8"
      ]
    },
    {
      "name": "get_vault_tokens",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>"
      ],
      "return": [
        "u64",
        "u64",
        "u64",
        "u64",
        "vector<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::RewardRecord>"
      ]
    },
    {
      "name": "rebalance",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>",
        "u32",
        "u32",
        "u64",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "remove_as_pair",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>",
        "u64"
      ],
      "return": []
    },
    {
      "name": "remove_as_single",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>",
        "bool",
        "address",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64"
      ],
      "return": []
    },
    {
      "name": "start_vault",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>"
      ],
      "return": []
    },
    {
      "name": "stop_vault",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>"
      ],
      "return": []
    },
    {
      "name": "swap_liquidity_token_to_another",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>",
        "0x1::object::Object<0x7730cd28ee1cdc9e999336cbc430f99e7c44397c0aa77516f6f23a78559bb5::pool::Pool>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "swap_liquidity_token_to_another_then_compound",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>",
        "address",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64",
        "bool"
      ],
      "return": []
    },
    {
      "name": "swap_rewards_token_to_another",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>",
        "vector<address>",
        "u64",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "update_performance_fee",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>",
        "u64"
      ],
      "return": []
    },
    {
      "name": "update_vault_cap",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::vaults::Vault>",
        "u64"
      ],
      "return": []
    }
  ],
  "structs": [
    {
      "name": "RewardRecord",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "copy",
        "drop"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "rewards_fa",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "Vault",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "store",
        "key"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "lp_token_refs",
          "type": "0x19bcbcf8e688fd5ddf52725807bc8bf455a76d4b5a6021cfdc4b5b2652e5cd55::lp::LPTokenRefs"
        },
        {
          "name": "share_cap",
          "type": "u64"
        },
        {
          "name": "pool",
          "type": "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>"
        },
        {
          "name": "position_id",
          "type": "address"
        },
        {
          "name": "total_shares",
          "type": "u64"
        },
        {
          "name": "performance_fee_rate",
          "type": "u64"
        },
        {
          "name": "withdraw_fee_rate",
          "type": "u64"
        },
        {
          "name": "deposit_fee_rate",
          "type": "u64"
        },
        {
          "name": "fee_receiver",
          "type": "vector<address>"
        },
        {
          "name": "fee_share",
          "type": "vector<u64>"
        },
        {
          "name": "token_a",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_b",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "fee_tier",
          "type": "u8"
        },
        {
          "name": "rewards_meta_list",
          "type": "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
        },
        {
          "name": "token_a_store",
          "type": "0x1::object::Object<0x1::fungible_asset::FungibleStore>"
        },
        {
          "name": "token_b_store",
          "type": "0x1::object::Object<0x1::fungible_asset::FungibleStore>"
        },
        {
          "name": "rewards_list",
          "type": "vector<0x1::object::Object<0x1::fungible_asset::FungibleStore>>"
        },
        {
          "name": "pause",
          "type": "bool"
        },
        {
          "name": "vault_name",
          "type": "0x1::string::String"
        }
      ]
    },
    {
      "name": "VaultClosedPositionEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "vault_id",
          "type": "address"
        },
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "token_a",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_b",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "closed_position_id",
          "type": "address"
        },
        {
          "name": "pool_current_sqrt_price",
          "type": "u128"
        },
        {
          "name": "pool_current_tick",
          "type": "u32"
        }
      ]
    },
    {
      "name": "VaultCompoundedEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "sender",
          "type": "address"
        },
        {
          "name": "vault_id",
          "type": "address"
        },
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "position_id",
          "type": "address"
        },
        {
          "name": "token_a",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_b",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_a_amount_in",
          "type": "u64"
        },
        {
          "name": "token_b_amount_in",
          "type": "u64"
        }
      ]
    },
    {
      "name": "VaultCreatedEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "sender",
          "type": "address"
        },
        {
          "name": "vault_id",
          "type": "address"
        },
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "position_id",
          "type": "address"
        },
        {
          "name": "token_a",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_b",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "tick_lower",
          "type": "u32"
        },
        {
          "name": "tick_upper",
          "type": "u32"
        },
        {
          "name": "performance_fee_rate",
          "type": "u64"
        },
        {
          "name": "withdraw_fee_rate",
          "type": "u64"
        },
        {
          "name": "deposit_fee_rate",
          "type": "u64"
        },
        {
          "name": "fee_receiver",
          "type": "vector<address>"
        },
        {
          "name": "fee_share",
          "type": "vector<u64>"
        },
        {
          "name": "pool_current_sqrt_price",
          "type": "u128"
        },
        {
          "name": "pool_current_tick",
          "type": "u32"
        },
        {
          "name": "vault_name",
          "type": "0x1::string::String"
        }
      ]
    },
    {
      "name": "VaultDepositedWithPairEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "sender",
          "type": "address"
        },
        {
          "name": "vault_id",
          "type": "address"
        },
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "position_id",
          "type": "address"
        },
        {
          "name": "tick_lower",
          "type": "u32"
        },
        {
          "name": "tick_upper",
          "type": "u32"
        },
        {
          "name": "pool_current_sqrt_price",
          "type": "u128"
        },
        {
          "name": "pool_current_tick",
          "type": "u32"
        },
        {
          "name": "token_a",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_b",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_a_amount",
          "type": "u64"
        },
        {
          "name": "token_b_amount",
          "type": "u64"
        },
        {
          "name": "added_shares",
          "type": "u64"
        }
      ]
    },
    {
      "name": "VaultDepositedWithPairEventV2",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "sender",
          "type": "address"
        },
        {
          "name": "vault_id",
          "type": "address"
        },
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "position_id",
          "type": "address"
        },
        {
          "name": "tick_lower",
          "type": "u32"
        },
        {
          "name": "tick_upper",
          "type": "u32"
        },
        {
          "name": "pool_current_sqrt_price",
          "type": "u128"
        },
        {
          "name": "pool_current_tick",
          "type": "u32"
        },
        {
          "name": "token_a",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_b",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_a_amount",
          "type": "u64"
        },
        {
          "name": "token_b_amount",
          "type": "u64"
        },
        {
          "name": "added_shares",
          "type": "u64"
        },
        {
          "name": "current_shares",
          "type": "u64"
        }
      ]
    },
    {
      "name": "VaultDepositedWithSingleEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "sender",
          "type": "address"
        },
        {
          "name": "vault_id",
          "type": "address"
        },
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "position_id",
          "type": "address"
        },
        {
          "name": "tick_lower",
          "type": "u32"
        },
        {
          "name": "tick_upper",
          "type": "u32"
        },
        {
          "name": "pool_current_sqrt_price",
          "type": "u128"
        },
        {
          "name": "pool_current_tick",
          "type": "u32"
        },
        {
          "name": "a_or_b",
          "type": "bool"
        },
        {
          "name": "token",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_amount_in",
          "type": "u64"
        },
        {
          "name": "added_shares",
          "type": "u64"
        }
      ]
    },
    {
      "name": "VaultDepositedWithSingleEventV2",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "sender",
          "type": "address"
        },
        {
          "name": "vault_id",
          "type": "address"
        },
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "position_id",
          "type": "address"
        },
        {
          "name": "tick_lower",
          "type": "u32"
        },
        {
          "name": "tick_upper",
          "type": "u32"
        },
        {
          "name": "pool_current_sqrt_price",
          "type": "u128"
        },
        {
          "name": "pool_current_tick",
          "type": "u32"
        },
        {
          "name": "a_or_b",
          "type": "bool"
        },
        {
          "name": "token",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_amount_in",
          "type": "u64"
        },
        {
          "name": "added_shares",
          "type": "u64"
        },
        {
          "name": "current_shares",
          "type": "u64"
        }
      ]
    },
    {
      "name": "VaultFeeUpdatedEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "sender",
          "type": "address"
        },
        {
          "name": "vault_id",
          "type": "address"
        },
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "position_id",
          "type": "address"
        },
        {
          "name": "performance_fee_rate",
          "type": "u64"
        },
        {
          "name": "withdraw_fee_rate",
          "type": "u64"
        },
        {
          "name": "deposit_fee_rate",
          "type": "u64"
        },
        {
          "name": "fee_receiver",
          "type": "vector<address>"
        },
        {
          "name": "fee_share",
          "type": "vector<u64>"
        }
      ]
    },
    {
      "name": "VaultRebalancedEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "sender",
          "type": "address"
        },
        {
          "name": "vault_id",
          "type": "address"
        },
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "token_a",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_b",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "new_position_id",
          "type": "address"
        },
        {
          "name": "tick_lower_after",
          "type": "u32"
        },
        {
          "name": "tick_upper_after",
          "type": "u32"
        },
        {
          "name": "pool_current_sqrt_price",
          "type": "u128"
        },
        {
          "name": "pool_current_tick",
          "type": "u32"
        }
      ]
    },
    {
      "name": "VaultRemovedWithPairEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "sender",
          "type": "address"
        },
        {
          "name": "vault_id",
          "type": "address"
        },
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "position_id",
          "type": "address"
        },
        {
          "name": "tick_lower",
          "type": "u32"
        },
        {
          "name": "tick_upper",
          "type": "u32"
        },
        {
          "name": "pool_current_sqrt_price",
          "type": "u128"
        },
        {
          "name": "pool_current_tick",
          "type": "u32"
        },
        {
          "name": "token_a",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_b",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_a_amount",
          "type": "u64"
        },
        {
          "name": "token_b_amount",
          "type": "u64"
        },
        {
          "name": "removed_shares",
          "type": "u64"
        }
      ]
    },
    {
      "name": "VaultRemovedWithPairEventV2",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "sender",
          "type": "address"
        },
        {
          "name": "vault_id",
          "type": "address"
        },
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "position_id",
          "type": "address"
        },
        {
          "name": "tick_lower",
          "type": "u32"
        },
        {
          "name": "tick_upper",
          "type": "u32"
        },
        {
          "name": "pool_current_sqrt_price",
          "type": "u128"
        },
        {
          "name": "pool_current_tick",
          "type": "u32"
        },
        {
          "name": "token_a",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_b",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_a_amount",
          "type": "u64"
        },
        {
          "name": "token_b_amount",
          "type": "u64"
        },
        {
          "name": "removed_shares",
          "type": "u64"
        },
        {
          "name": "current_shares",
          "type": "u64"
        }
      ]
    },
    {
      "name": "VaultRemovedWithSingleEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "sender",
          "type": "address"
        },
        {
          "name": "vault_id",
          "type": "address"
        },
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "position_id",
          "type": "address"
        },
        {
          "name": "tick_lower",
          "type": "u32"
        },
        {
          "name": "tick_upper",
          "type": "u32"
        },
        {
          "name": "pool_current_sqrt_price",
          "type": "u128"
        },
        {
          "name": "pool_current_tick",
          "type": "u32"
        },
        {
          "name": "token",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "a_or_b",
          "type": "bool"
        },
        {
          "name": "token_amount",
          "type": "u64"
        },
        {
          "name": "removed_shares",
          "type": "u64"
        }
      ]
    },
    {
      "name": "VaultRemovedWithSingleEventV2",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "sender",
          "type": "address"
        },
        {
          "name": "vault_id",
          "type": "address"
        },
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "position_id",
          "type": "address"
        },
        {
          "name": "tick_lower",
          "type": "u32"
        },
        {
          "name": "tick_upper",
          "type": "u32"
        },
        {
          "name": "pool_current_sqrt_price",
          "type": "u128"
        },
        {
          "name": "pool_current_tick",
          "type": "u32"
        },
        {
          "name": "token",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "a_or_b",
          "type": "bool"
        },
        {
          "name": "token_amount",
          "type": "u64"
        },
        {
          "name": "removed_shares",
          "type": "u64"
        },
        {
          "name": "current_shares",
          "type": "u64"
        }
      ]
    },
    {
      "name": "VaultRewardsToLiquidityEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "sender",
          "type": "address"
        },
        {
          "name": "vault_id",
          "type": "address"
        },
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "position_id",
          "type": "address"
        },
        {
          "name": "token_reward",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_liquidity",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "reward_token_amount",
          "type": "u64"
        },
        {
          "name": "liquidity_token_amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "Vault_fee_and_reward_share",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "receiver",
          "type": "address"
        },
        {
          "name": "fee_type",
          "type": "0x1::string::String"
        },
        {
          "name": "coin",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "amount",
          "type": "u64"
        },
        {
          "name": "time",
          "type": "u64"
        }
      ]
    }
  ]
} as const;
