// This file is auto-generated by the generate-abis.ts script
export const hyperion_router_v3_abi = {
  "address": "0x0",
  "name": "router_v3",
  "friends": [],
  "exposed_functions": [
    {
      "name": "get_amount_by_liquidity",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>"
      ],
      "return": [
        "u64",
        "u64"
      ]
    },
    {
      "name": "add_incentive",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "u64",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64"
      ],
      "return": []
    },
    {
      "name": "add_rewarder",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "claim_rewards",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>",
        "address"
      ],
      "return": []
    },
    {
      "name": "remove_incentive",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "update_emissions_rate",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "add_liquidity",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "claim_fees",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "vector<address>",
        "address"
      ],
      "return": []
    },
    {
      "name": "open_position",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8",
        "u32",
        "u32",
        "u64"
      ],
      "return": []
    },
    {
      "name": "remove_liquidity",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>",
        "u128",
        "u64",
        "u64",
        "address",
        "u64"
      ],
      "return": []
    },
    {
      "name": "add_coin_incentive",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "add_coin_incentive_v2",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "add_incentive_v2",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "u64",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "create_pool",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8",
        "u32"
      ],
      "return": []
    },
    {
      "name": "exact_input_asset_for_coin_entry",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "u8",
        "u64",
        "u64",
        "u128",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "address",
        "u64"
      ],
      "return": []
    },
    {
      "name": "exact_input_coin_for_asset_entry",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "u8",
        "u64",
        "u64",
        "u128",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "address",
        "u64"
      ],
      "return": []
    },
    {
      "name": "exact_input_coin_for_coin_entry",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        },
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "u8",
        "u64",
        "u64",
        "u128",
        "address",
        "u64"
      ],
      "return": []
    },
    {
      "name": "exact_input_swap_entry",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u8",
        "u64",
        "u64",
        "u128",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "address",
        "u64"
      ],
      "return": []
    },
    {
      "name": "exact_output_asset_for_coin_entry",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "u8",
        "u64",
        "u64",
        "u128",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "address",
        "u64"
      ],
      "return": []
    },
    {
      "name": "exact_output_coin_for_asset_entry",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "u8",
        "u64",
        "u64",
        "u128",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "address",
        "u64"
      ],
      "return": []
    },
    {
      "name": "exact_output_coin_for_coin_entry",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        },
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "u8",
        "u64",
        "u64",
        "u128",
        "address",
        "u64"
      ],
      "return": []
    },
    {
      "name": "exact_output_swap_entry",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u8",
        "u64",
        "u64",
        "u128",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "address",
        "u64"
      ],
      "return": []
    },
    {
      "name": "swap_batch",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "vector<address>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "u64",
        "address"
      ],
      "return": []
    },
    {
      "name": "swap_batch_coin_directly_deposit_entry",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "vector<address>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "swap_batch_coin_entry",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "vector<address>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "u64",
        "address"
      ],
      "return": []
    },
    {
      "name": "swap_batch_directly_deposit",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "vector<address>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "add_coin_rewarder",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "add_liquidity_both_coins",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        },
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>",
        "u8",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "add_liquidity_by_contract",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>",
        "u64",
        "u64",
        "u64",
        "u64",
        "0x1::fungible_asset::FungibleAsset",
        "0x1::fungible_asset::FungibleAsset",
        "u64"
      ],
      "return": [
        "u64",
        "u64",
        "0x1::fungible_asset::FungibleAsset",
        "0x1::fungible_asset::FungibleAsset"
      ]
    },
    {
      "name": "add_liquidity_coin",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "add_liquidity_single",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "u256",
        "u256",
        "u256",
        "u256"
      ],
      "return": []
    },
    {
      "name": "add_liquidity_single_coins",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "u256",
        "u256",
        "u256",
        "u256"
      ],
      "return": []
    },
    {
      "name": "apt_transfer_to_coin",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer"
      ],
      "return": []
    },
    {
      "name": "claim_fees_and_rewards",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "vector<address>",
        "address"
      ],
      "return": []
    },
    {
      "name": "claim_fees_and_rewards_directly_deposit",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "vector<address>"
      ],
      "return": []
    },
    {
      "name": "create_liquidity",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8",
        "u32",
        "u32",
        "u32",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "create_liquidity_both_coins",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        },
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "u8",
        "u32",
        "u32",
        "u32",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "create_liquidity_coin",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8",
        "u32",
        "u32",
        "u32",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "create_liquidity_single",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8",
        "u32",
        "u32",
        "u64",
        "u256",
        "u256",
        "u256",
        "u256"
      ],
      "return": []
    },
    {
      "name": "create_liquidity_single_coins",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8",
        "u32",
        "u32",
        "u64",
        "u256",
        "u256",
        "u256",
        "u256"
      ],
      "return": []
    },
    {
      "name": "create_pool_both_coins",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        },
        {
          "constraints": []
        }
      ],
      "params": [
        "u8",
        "u32"
      ],
      "return": []
    },
    {
      "name": "create_pool_coin",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8",
        "u32"
      ],
      "return": []
    },
    {
      "name": "get_batch_amount_in",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "vector<address>",
        "u64",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "get_batch_amount_out",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "vector<address>",
        "u64",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "open_position_both_coins",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        },
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "u8",
        "u32",
        "u32",
        "u64"
      ],
      "return": []
    },
    {
      "name": "open_position_coin",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8",
        "u32",
        "u32",
        "u64"
      ],
      "return": []
    },
    {
      "name": "optimal_liquidity_amounts",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u32",
        "u32",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8",
        "u64",
        "u64",
        "u64",
        "u64"
      ],
      "return": [
        "u128",
        "u64",
        "u64"
      ]
    },
    {
      "name": "optimal_liquidity_amounts_from_a",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u32",
        "u32",
        "u32",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8",
        "u64",
        "u64",
        "u64"
      ],
      "return": [
        "u128",
        "u64"
      ]
    },
    {
      "name": "optimal_liquidity_amounts_from_b",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u32",
        "u32",
        "u32",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8",
        "u64",
        "u64",
        "u64"
      ],
      "return": [
        "u128",
        "u64"
      ]
    },
    {
      "name": "remove_liquidity_both_coins",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        },
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>",
        "u128",
        "u64",
        "u64",
        "address",
        "u64"
      ],
      "return": []
    },
    {
      "name": "remove_liquidity_both_coins_directly_deposit",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        },
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>",
        "u128",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "remove_liquidity_by_contract",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>",
        "u128",
        "u64",
        "u64",
        "u64"
      ],
      "return": [
        "0x1::option::Option<0x1::fungible_asset::FungibleAsset>",
        "0x1::option::Option<0x1::fungible_asset::FungibleAsset>"
      ]
    },
    {
      "name": "remove_liquidity_by_contract_with_second_signer",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>",
        "u128",
        "u64",
        "u64",
        "u64"
      ],
      "return": [
        "0x1::option::Option<0x1::fungible_asset::FungibleAsset>",
        "0x1::option::Option<0x1::fungible_asset::FungibleAsset>"
      ]
    },
    {
      "name": "remove_liquidity_coin",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>",
        "u128",
        "u64",
        "u64",
        "address",
        "u64"
      ],
      "return": []
    },
    {
      "name": "remove_liquidity_coin_directly_deposit",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>",
        "u128",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "remove_liquidity_directly_deposit",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>",
        "u128",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "remove_liquidity_single",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>",
        "u128",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u256",
        "u256"
      ],
      "return": []
    },
    {
      "name": "remove_liquidity_single_coins",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>",
        "u128",
        "u256",
        "u256"
      ],
      "return": []
    },
    {
      "name": "remove_liquidity_single_with_multiagent",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "&signer",
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>",
        "u128",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u256",
        "u256"
      ],
      "return": []
    },
    {
      "name": "remove_liquidity_with_multiagent",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "&signer",
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>",
        "u128",
        "u64",
        "u64",
        "address",
        "u64"
      ],
      "return": []
    },
    {
      "name": "remove_liquidity_with_multiagent_directly_deposit",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "&signer",
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>",
        "u128",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    }
  ],
  "structs": [
    {
      "name": "AddSingleLiquidityEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "caller",
          "type": "address"
        },
        {
          "name": "position",
          "type": "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>"
        },
        {
          "name": "input_amount",
          "type": "u64"
        },
        {
          "name": "swap_from",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "swap_to",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "swap_amount_in",
          "type": "u64"
        },
        {
          "name": "swap_amount_out",
          "type": "u64"
        },
        {
          "name": "delta_lp_amount",
          "type": "u128"
        },
        {
          "name": "add_amount_a",
          "type": "u64"
        },
        {
          "name": "add_amount_b",
          "type": "u64"
        }
      ]
    },
    {
      "name": "RemoveSingleLiquidityEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "caller",
          "type": "address"
        },
        {
          "name": "position",
          "type": "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>"
        },
        {
          "name": "swap_from",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "swap_to",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "swap_amount_in",
          "type": "u64"
        },
        {
          "name": "swap_amount_out",
          "type": "u64"
        },
        {
          "name": "delta_lp_amount",
          "type": "u128"
        },
        {
          "name": "remove_amount_a",
          "type": "u64"
        },
        {
          "name": "remove_amount_b",
          "type": "u64"
        },
        {
          "name": "output_amount",
          "type": "u64"
        }
      ]
    }
  ]
} as const;
