// This file is auto-generated by the generate-abis.ts script
export const hyperion_pool_v3_abi = {
  "address": "0x0",
  "name": "pool_v3",
  "friends": [
    "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::router_v3"
  ],
  "exposed_functions": [
    {
      "name": "swap",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "bool",
        "bool",
        "u64",
        "0x1::fungible_asset::FungibleAsset",
        "u128"
      ],
      "return": [
        "u64",
        "0x1::fungible_asset::FungibleAsset",
        "0x1::fungible_asset::FungibleAsset"
      ]
    },
    {
      "name": "initialize",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [],
      "return": []
    },
    {
      "name": "is_initialized",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "bool"
      ]
    },
    {
      "name": "update_net_only",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "address",
        "u128",
        "u32",
        "u32"
      ],
      "return": []
    },
    {
      "name": "add_incentive",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "u64",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64"
      ],
      "return": []
    },
    {
      "name": "add_rewarder",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "claim_rewards",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>"
      ],
      "return": [
        "vector<0x1::fungible_asset::FungibleAsset>"
      ]
    },
    {
      "name": "remove_incentive",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "remove_incentive_to_pause",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "u64"
      ],
      "return": []
    },
    {
      "name": "update_emissions_rate",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "update_emissions_rate_max",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "update_rewarder_owed",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "address",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "add_liquidity",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>",
        "u128",
        "0x1::fungible_asset::FungibleAsset",
        "0x1::fungible_asset::FungibleAsset"
      ],
      "return": [
        "u64",
        "u64",
        "0x1::fungible_asset::FungibleAsset",
        "0x1::fungible_asset::FungibleAsset"
      ]
    },
    {
      "name": "claim_fees",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>"
      ],
      "return": [
        "0x1::fungible_asset::FungibleAsset",
        "0x1::fungible_asset::FungibleAsset"
      ]
    },
    {
      "name": "open_position",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8",
        "u32",
        "u32"
      ],
      "return": [
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>"
      ]
    },
    {
      "name": "remove_liquidity",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>",
        "u128"
      ],
      "return": [
        "0x1::option::Option<0x1::fungible_asset::FungibleAsset>",
        "0x1::option::Option<0x1::fungible_asset::FungibleAsset>"
      ]
    },
    {
      "name": "remove_liquidity_v2",
      "visibility": "friend",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>",
        "u128"
      ],
      "return": [
        "0x1::option::Option<0x1::fungible_asset::FungibleAsset>",
        "0x1::option::Option<0x1::fungible_asset::FungibleAsset>"
      ]
    },
    {
      "name": "current_tick",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8"
      ],
      "return": [
        "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::i32::I32"
      ]
    },
    {
      "name": "add_blocked_position_to_new_blacklist",
      "visibility": "private",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "address",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>"
      ],
      "return": []
    },
    {
      "name": "add_coin_incentive",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "add_coin_incentive_v2",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "add_incentive_v2",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "u64",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "add_liquidity_v2",
      "visibility": "friend",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>",
        "u128",
        "0x1::fungible_asset::FungibleAsset",
        "0x1::fungible_asset::FungibleAsset"
      ],
      "return": [
        "u64",
        "u64",
        "0x1::fungible_asset::FungibleAsset",
        "0x1::fungible_asset::FungibleAsset"
      ]
    },
    {
      "name": "add_rewarder_coin",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "all_pools",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "vector<0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>>"
      ]
    },
    {
      "name": "all_pools_with_info",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u64",
        "u64"
      ],
      "return": [
        "vector<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolInfoV3>",
        "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::PageInfo"
      ]
    },
    {
      "name": "block_position",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>"
      ],
      "return": []
    },
    {
      "name": "block_position_batch",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "vector<0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>>"
      ],
      "return": []
    },
    {
      "name": "claim_protocol_fees_all",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8"
      ],
      "return": []
    },
    {
      "name": "create_pool",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8",
        "u32"
      ],
      "return": [
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>"
      ]
    },
    {
      "name": "current_price",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8"
      ],
      "return": [
        "u128"
      ]
    },
    {
      "name": "current_tick_and_price",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "u32",
        "u128"
      ]
    },
    {
      "name": "deposit_liquidity_token",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "address",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64"
      ],
      "return": []
    },
    {
      "name": "get_amount_in",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64"
      ],
      "return": [
        "u64",
        "u64"
      ]
    },
    {
      "name": "get_amount_out",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64"
      ],
      "return": [
        "u64",
        "u64"
      ]
    },
    {
      "name": "get_blocked_position",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>"
      ],
      "return": [
        "vector<address>"
      ]
    },
    {
      "name": "get_fee_rate",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u8"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "get_pending_fees",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>"
      ],
      "return": [
        "vector<u64>"
      ]
    },
    {
      "name": "get_pending_fees_blocked",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>"
      ],
      "return": [
        "vector<u64>"
      ]
    },
    {
      "name": "get_pending_rewards",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>"
      ],
      "return": [
        "vector<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::rewarder::PendingReward>"
      ]
    },
    {
      "name": "get_pending_rewards_blocked",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>"
      ],
      "return": [
        "vector<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::rewarder::PendingReward>"
      ]
    },
    {
      "name": "get_pool_liquidity",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>"
      ],
      "return": [
        "u128"
      ]
    },
    {
      "name": "get_pool_tick_info",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "u32"
      ],
      "return": [
        "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::tick::TickInfo"
      ]
    },
    {
      "name": "get_pool_tick_info_batch",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "vector<u32>"
      ],
      "return": [
        "vector<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::tick::TickInfo>"
      ]
    },
    {
      "name": "get_position_emission_rate",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>"
      ],
      "return": [
        "vector<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::rewarder::RewardRate>"
      ]
    },
    {
      "name": "get_protocol_fee_rate",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "get_protocol_fee_receiver",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "address"
      ]
    },
    {
      "name": "get_remaining_incentive",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>"
      ],
      "return": [
        "vector<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::rewarder::RemainingIncentive>"
      ]
    },
    {
      "name": "get_rewarder_numbers",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>"
      ],
      "return": [
        "vector<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::rewarder::Numbers>"
      ]
    },
    {
      "name": "get_tick_spacing",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "u8"
      ],
      "return": [
        "u32"
      ]
    },
    {
      "name": "liquidity_pool",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8"
      ],
      "return": [
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>"
      ]
    },
    {
      "name": "liquidity_pool_address",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8"
      ],
      "return": [
        "address"
      ]
    },
    {
      "name": "liquidity_pool_address_safe",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8"
      ],
      "return": [
        "bool",
        "address"
      ]
    },
    {
      "name": "liquidity_pool_exists",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8"
      ],
      "return": [
        "bool"
      ]
    },
    {
      "name": "liquidity_pool_info",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>"
      ],
      "return": [
        "vector<0x1::string::String>"
      ]
    },
    {
      "name": "liquidity_pool_info_both_coin",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [
        {
          "constraints": []
        },
        {
          "constraints": []
        }
      ],
      "params": [
        "u8"
      ],
      "return": [
        "vector<0x1::string::String>"
      ]
    },
    {
      "name": "liquidity_pool_info_both_fa",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8"
      ],
      "return": [
        "vector<0x1::string::String>"
      ]
    },
    {
      "name": "liquidity_pool_info_with_coin_fa",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8"
      ],
      "return": [
        "vector<0x1::string::String>"
      ]
    },
    {
      "name": "pause_pool",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>"
      ],
      "return": []
    },
    {
      "name": "pause_protocol",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer"
      ],
      "return": []
    },
    {
      "name": "pause_rewarder_manager",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>"
      ],
      "return": []
    },
    {
      "name": "pool_next_initialize_tick",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "bool"
      ],
      "return": [
        "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::i32::I32",
        "bool"
      ]
    },
    {
      "name": "pool_reserve_amount",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>"
      ],
      "return": [
        "u64",
        "u64"
      ]
    },
    {
      "name": "pool_rewarder_list",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>"
      ],
      "return": [
        "vector<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::rewarder::Rewarder>"
      ]
    },
    {
      "name": "remove_position_block",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>"
      ],
      "return": []
    },
    {
      "name": "restart_rewarder_manager",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>"
      ],
      "return": []
    },
    {
      "name": "resume_pool",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>"
      ],
      "return": []
    },
    {
      "name": "set_protocol_fee_receiver",
      "visibility": "private",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "address"
      ],
      "return": []
    },
    {
      "name": "start_protocol",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer"
      ],
      "return": []
    },
    {
      "name": "supported_inner_assets",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>"
      ],
      "return": [
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
      ]
    },
    {
      "name": "update_pool_liquidity",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "address",
        "u128"
      ],
      "return": []
    },
    {
      "name": "update_protocol_fee_rate",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "u64"
      ],
      "return": []
    },
    {
      "name": "update_remove_liquidity_amount",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "address",
        "u128",
        "u32",
        "u32"
      ],
      "return": []
    },
    {
      "name": "update_reward_amount",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "address",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64"
      ],
      "return": []
    },
    {
      "name": "withdraw_temporary_coin",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "u64",
        "address"
      ],
      "return": []
    },
    {
      "name": "withdraw_temporary_token",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "address"
      ],
      "return": []
    }
  ],
  "structs": [
    {
      "name": "AddLiquidityEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "object_id",
          "type": "address"
        },
        {
          "name": "token_a",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_b",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "fee_tier",
          "type": "u8"
        },
        {
          "name": "is_delete",
          "type": "bool"
        },
        {
          "name": "added_lp_amount",
          "type": "u128"
        },
        {
          "name": "previous_liquidity_amount",
          "type": "u128"
        },
        {
          "name": "amount_a",
          "type": "u64"
        },
        {
          "name": "amount_b",
          "type": "u64"
        }
      ]
    },
    {
      "name": "AddLiquidityEventV2",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "object_id",
          "type": "address"
        },
        {
          "name": "token_a",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_b",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "fee_tier",
          "type": "u8"
        },
        {
          "name": "is_delete",
          "type": "bool"
        },
        {
          "name": "added_lp_amount",
          "type": "u128"
        },
        {
          "name": "previous_liquidity_amount",
          "type": "u128"
        },
        {
          "name": "amount_a",
          "type": "u64"
        },
        {
          "name": "amount_b",
          "type": "u64"
        },
        {
          "name": "pool_reserve_a",
          "type": "u64"
        },
        {
          "name": "pool_reserve_b",
          "type": "u64"
        }
      ]
    },
    {
      "name": "AddLiquidityEventV3",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "object_id",
          "type": "address"
        },
        {
          "name": "token_a",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_b",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "fee_tier",
          "type": "u8"
        },
        {
          "name": "is_delete",
          "type": "bool"
        },
        {
          "name": "added_lp_amount",
          "type": "u128"
        },
        {
          "name": "previous_liquidity_amount",
          "type": "u128"
        },
        {
          "name": "amount_a",
          "type": "u64"
        },
        {
          "name": "amount_b",
          "type": "u64"
        },
        {
          "name": "pool_reserve_a",
          "type": "u64"
        },
        {
          "name": "pool_reserve_b",
          "type": "u64"
        },
        {
          "name": "current_tick",
          "type": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::i32::I32"
        },
        {
          "name": "sqrt_price",
          "type": "u128"
        },
        {
          "name": "active_liquidity",
          "type": "u128"
        }
      ]
    },
    {
      "name": "ClaimFeesEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool",
          "type": "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>"
        },
        {
          "name": "lp_object",
          "type": "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>"
        },
        {
          "name": "token",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "amount",
          "type": "u64"
        },
        {
          "name": "owner",
          "type": "address"
        }
      ]
    },
    {
      "name": "ClaimFeesEventV2",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool",
          "type": "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>"
        },
        {
          "name": "lp_object",
          "type": "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>"
        },
        {
          "name": "token",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "amount",
          "type": "u64"
        },
        {
          "name": "owner",
          "type": "address"
        },
        {
          "name": "token_a_liquidity_after_claim",
          "type": "u64"
        },
        {
          "name": "token_b_liquidity_after_claim",
          "type": "u64"
        }
      ]
    },
    {
      "name": "CreatePoolEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool",
          "type": "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>"
        },
        {
          "name": "token_a",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_b",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "fee_rate",
          "type": "u64"
        },
        {
          "name": "fee_tier",
          "type": "u8"
        },
        {
          "name": "sqrt_price",
          "type": "u128"
        },
        {
          "name": "tick",
          "type": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::i32::I32"
        }
      ]
    },
    {
      "name": "LiquidityPoolConfigsV3",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "key"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "all_pools",
          "type": "0x1::smart_vector::SmartVector<0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>>"
        },
        {
          "name": "is_paused",
          "type": "bool"
        },
        {
          "name": "fee_manager",
          "type": "address"
        },
        {
          "name": "pauser",
          "type": "address"
        },
        {
          "name": "pending_fee_manager",
          "type": "address"
        },
        {
          "name": "pending_pauser",
          "type": "address"
        },
        {
          "name": "tick_spacing_list",
          "type": "vector<u64>"
        }
      ]
    },
    {
      "name": "LiquidityPoolInfoV3",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "copy",
        "drop"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool",
          "type": "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>"
        },
        {
          "name": "token_a",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_b",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "fee_rate",
          "type": "u64"
        },
        {
          "name": "token_a_reserve",
          "type": "u64"
        },
        {
          "name": "token_b_reserve",
          "type": "u64"
        },
        {
          "name": "liquidity_total",
          "type": "u128"
        }
      ]
    },
    {
      "name": "LiquidityPoolV3",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "key"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "token_a_liquidity",
          "type": "0x1::object::Object<0x1::fungible_asset::FungibleStore>"
        },
        {
          "name": "token_b_liquidity",
          "type": "0x1::object::Object<0x1::fungible_asset::FungibleStore>"
        },
        {
          "name": "token_a_fee",
          "type": "0x1::object::Object<0x1::fungible_asset::FungibleStore>"
        },
        {
          "name": "token_b_fee",
          "type": "0x1::object::Object<0x1::fungible_asset::FungibleStore>"
        },
        {
          "name": "sqrt_price",
          "type": "u128"
        },
        {
          "name": "liquidity",
          "type": "u128"
        },
        {
          "name": "tick",
          "type": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::i32::I32"
        },
        {
          "name": "observation_index",
          "type": "u64"
        },
        {
          "name": "observation_cardinality",
          "type": "u64"
        },
        {
          "name": "observation_cardinality_next",
          "type": "u64"
        },
        {
          "name": "fee_rate",
          "type": "u64"
        },
        {
          "name": "fee_protocol",
          "type": "u64"
        },
        {
          "name": "unlocked",
          "type": "bool"
        },
        {
          "name": "fee_growth_global_a",
          "type": "u128"
        },
        {
          "name": "fee_growth_global_b",
          "type": "u128"
        },
        {
          "name": "seconds_per_liquidity_oracle",
          "type": "u128"
        },
        {
          "name": "seconds_per_liquidity_incentive",
          "type": "u128"
        },
        {
          "name": "position_blacklist",
          "type": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_blacklist::PositionBlackList"
        },
        {
          "name": "last_update_timestamp",
          "type": "u64"
        },
        {
          "name": "tick_info",
          "type": "0x1::smart_table::SmartTable<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::i32::I32, 0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::tick::TickInfo>"
        },
        {
          "name": "tick_map",
          "type": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::tick_bitmap::BitMap"
        },
        {
          "name": "tick_spacing",
          "type": "u32"
        },
        {
          "name": "protocol_fees",
          "type": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::ProtocolFees"
        },
        {
          "name": "lp_token_refs",
          "type": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::lp::LPTokenRefs"
        },
        {
          "name": "max_liquidity_per_tick",
          "type": "u128"
        },
        {
          "name": "rewarder_manager",
          "type": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::rewarder::RewarderManager"
        }
      ]
    },
    {
      "name": "PageInfo",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "copy",
        "drop"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "offset",
          "type": "u64"
        },
        {
          "name": "limit",
          "type": "u64"
        },
        {
          "name": "total",
          "type": "u64"
        },
        {
          "name": "take",
          "type": "u64"
        }
      ]
    },
    {
      "name": "PoolSnapshot",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "sqrt_price",
          "type": "u128"
        },
        {
          "name": "liquidity",
          "type": "u128"
        },
        {
          "name": "tick",
          "type": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::i32::I32"
        },
        {
          "name": "observation_index",
          "type": "u64"
        },
        {
          "name": "observation_cardinality",
          "type": "u64"
        },
        {
          "name": "observation_cardinality_next",
          "type": "u64"
        },
        {
          "name": "fee_rate",
          "type": "u64"
        },
        {
          "name": "fee_rate_denominatore",
          "type": "u64"
        },
        {
          "name": "fee_growth_global_a",
          "type": "u128"
        },
        {
          "name": "fee_growth_global_b",
          "type": "u128"
        },
        {
          "name": "tick_spacing",
          "type": "u32"
        }
      ]
    },
    {
      "name": "PoolSnapshotV2",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "sqrt_price",
          "type": "u128"
        },
        {
          "name": "liquidity",
          "type": "u128"
        },
        {
          "name": "tick",
          "type": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::i32::I32"
        },
        {
          "name": "observation_index",
          "type": "u64"
        },
        {
          "name": "observation_cardinality",
          "type": "u64"
        },
        {
          "name": "observation_cardinality_next",
          "type": "u64"
        },
        {
          "name": "fee_rate",
          "type": "u64"
        },
        {
          "name": "fee_rate_denominatore",
          "type": "u64"
        },
        {
          "name": "fee_growth_global_a",
          "type": "u128"
        },
        {
          "name": "fee_growth_global_b",
          "type": "u128"
        },
        {
          "name": "tick_spacing",
          "type": "u32"
        },
        {
          "name": "token_a_reserve",
          "type": "u64"
        },
        {
          "name": "token_b_reserve",
          "type": "u64"
        }
      ]
    },
    {
      "name": "PoolTemporaryStorage",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "key"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "stores",
          "type": "vector<0x1::object::Object<0x1::fungible_asset::FungibleStore>>"
        }
      ]
    },
    {
      "name": "ProtocolFees",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "token_a",
          "type": "0x1::object::Object<0x1::fungible_asset::FungibleStore>"
        },
        {
          "name": "token_b",
          "type": "0x1::object::Object<0x1::fungible_asset::FungibleStore>"
        }
      ]
    },
    {
      "name": "RemoveLiquidityEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "object_id",
          "type": "address"
        },
        {
          "name": "token_a",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_b",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "fee_tier",
          "type": "u8"
        },
        {
          "name": "is_delete",
          "type": "bool"
        },
        {
          "name": "burned_lp_amount",
          "type": "u128"
        },
        {
          "name": "previous_liquidity_amount",
          "type": "u128"
        },
        {
          "name": "amount_a",
          "type": "u64"
        },
        {
          "name": "amount_b",
          "type": "u64"
        }
      ]
    },
    {
      "name": "RemoveLiquidityEventV2",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "object_id",
          "type": "address"
        },
        {
          "name": "token_a",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_b",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "fee_tier",
          "type": "u8"
        },
        {
          "name": "is_delete",
          "type": "bool"
        },
        {
          "name": "burned_lp_amount",
          "type": "u128"
        },
        {
          "name": "previous_liquidity_amount",
          "type": "u128"
        },
        {
          "name": "amount_a",
          "type": "u64"
        },
        {
          "name": "amount_b",
          "type": "u64"
        },
        {
          "name": "pool_reserve_a",
          "type": "u64"
        },
        {
          "name": "pool_reserve_b",
          "type": "u64"
        }
      ]
    },
    {
      "name": "RemoveLiquidityEventV3",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "object_id",
          "type": "address"
        },
        {
          "name": "token_a",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_b",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "fee_tier",
          "type": "u8"
        },
        {
          "name": "is_delete",
          "type": "bool"
        },
        {
          "name": "burned_lp_amount",
          "type": "u128"
        },
        {
          "name": "previous_liquidity_amount",
          "type": "u128"
        },
        {
          "name": "amount_a",
          "type": "u64"
        },
        {
          "name": "amount_b",
          "type": "u64"
        },
        {
          "name": "pool_reserve_a",
          "type": "u64"
        },
        {
          "name": "pool_reserve_b",
          "type": "u64"
        },
        {
          "name": "current_tick",
          "type": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::i32::I32"
        },
        {
          "name": "sqrt_price",
          "type": "u128"
        },
        {
          "name": "active_liquidity",
          "type": "u128"
        }
      ]
    },
    {
      "name": "StepComputations",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "sqrt_price_current",
          "type": "u128"
        },
        {
          "name": "sqrt_price_next",
          "type": "u128"
        },
        {
          "name": "amount_in",
          "type": "u64"
        },
        {
          "name": "amount_out",
          "type": "u64"
        },
        {
          "name": "fee_amount",
          "type": "u64"
        },
        {
          "name": "current_liquidity",
          "type": "u128"
        }
      ]
    },
    {
      "name": "SwapAfterEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "tick",
          "type": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::i32::I32"
        },
        {
          "name": "sqrt_price",
          "type": "u128"
        },
        {
          "name": "liquidity",
          "type": "u128"
        }
      ]
    },
    {
      "name": "SwapBeforeEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "tick",
          "type": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::i32::I32"
        },
        {
          "name": "sqrt_price",
          "type": "u128"
        },
        {
          "name": "liquidity",
          "type": "u128"
        }
      ]
    },
    {
      "name": "SwapEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "from_token",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "to_token",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "amount_in",
          "type": "u64"
        },
        {
          "name": "amount_out",
          "type": "u64"
        },
        {
          "name": "fee_amount",
          "type": "u64"
        },
        {
          "name": "protocol_fee_amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "SwapEventV2",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "from_token",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "to_token",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "amount_in",
          "type": "u64"
        },
        {
          "name": "amount_out",
          "type": "u64"
        },
        {
          "name": "fee_amount",
          "type": "u64"
        },
        {
          "name": "protocol_fee_amount",
          "type": "u64"
        },
        {
          "name": "pool_reserve_a",
          "type": "u64"
        },
        {
          "name": "pool_reserve_b",
          "type": "u64"
        }
      ]
    },
    {
      "name": "SwapEventV3",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "from_token",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "to_token",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "amount_in",
          "type": "u64"
        },
        {
          "name": "amount_out",
          "type": "u64"
        },
        {
          "name": "fee_amount",
          "type": "u64"
        },
        {
          "name": "protocol_fee_amount",
          "type": "u64"
        },
        {
          "name": "pool_reserve_a",
          "type": "u64"
        },
        {
          "name": "pool_reserve_b",
          "type": "u64"
        },
        {
          "name": "current_tick",
          "type": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::i32::I32"
        },
        {
          "name": "sqrt_price",
          "type": "u128"
        },
        {
          "name": "active_liquidity",
          "type": "u128"
        }
      ]
    },
    {
      "name": "SwapState",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "drop"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "amount_specified_remaining",
          "type": "u64"
        },
        {
          "name": "amount_calculated",
          "type": "u64"
        },
        {
          "name": "sqrt_price",
          "type": "u128"
        },
        {
          "name": "tick",
          "type": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::i32::I32"
        },
        {
          "name": "fee_growth_global",
          "type": "u128"
        },
        {
          "name": "seconds_per_liquidity",
          "type": "u128"
        },
        {
          "name": "protocol_fee",
          "type": "u64"
        },
        {
          "name": "liquidity",
          "type": "u128"
        },
        {
          "name": "fee_amount_total",
          "type": "u64"
        }
      ]
    },
    {
      "name": "UpdateRemoveLiqudityAmount",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "address"
        },
        {
          "name": "liquidity_delta",
          "type": "u128"
        },
        {
          "name": "tick_lower",
          "type": "u32"
        },
        {
          "name": "tick_upper",
          "type": "u32"
        }
      ]
    }
  ]
} as const;
