// This file is auto-generated by the generate-abis.ts script
export const moar_lens_abi = {
  "address": "0x0",
  "name": "lens",
  "friends": [],
  "exposed_functions": [
    {
      "name": "lp_token_metadata",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u64"
      ],
      "return": [
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ]
    },
    {
      "name": "get_all_ltvs_for_pool",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u64"
      ],
      "return": [
        "0x1::simple_map::SimpleMap<0x1::string::String, u64>"
      ]
    },
    {
      "name": "combine_asset_data",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "vector<0xeeaea90cd2a6a0d7a184a87a648aa43b2ffd871933f8b7d86638f584de856b7c::utils::AssetData>",
        "vector<0xeeaea90cd2a6a0d7a184a87a648aa43b2ffd871933f8b7d86638f584de856b7c::utils::AssetData>"
      ],
      "return": [
        "vector<0xeeaea90cd2a6a0d7a184a87a648aa43b2ffd871933f8b7d86638f584de856b7c::utils::AssetData>"
      ]
    },
    {
      "name": "get_credit_account_assets",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
      ]
    },
    {
      "name": "get_credit_account_combined_asset_amounts",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "vector<0xeeaea90cd2a6a0d7a184a87a648aa43b2ffd871933f8b7d86638f584de856b7c::utils::AssetData>"
      ]
    },
    {
      "name": "get_credit_account_debt_and_asset_amounts",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "vector<0xeeaea90cd2a6a0d7a184a87a648aa43b2ffd871933f8b7d86638f584de856b7c::utils::DebtData>",
        "vector<0xeeaea90cd2a6a0d7a184a87a648aa43b2ffd871933f8b7d86638f584de856b7c::utils::AssetData>"
      ]
    },
    {
      "name": "get_credit_account_debt_and_asset_values",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "u64",
        "u64"
      ]
    },
    {
      "name": "get_credit_account_debt_pools",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "vector<u64>"
      ]
    },
    {
      "name": "get_estimated_health_factor_clamm",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address",
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>",
        "vector<u64>",
        "vector<u64>",
        "vector<u64>",
        "u8",
        "address",
        "u128",
        "u32",
        "u32",
        "vector<u64>"
      ],
      "return": [
        "0x1::option::Option<u64>"
      ]
    },
    {
      "name": "get_estimated_health_metrics",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "bool",
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>",
        "vector<u64>",
        "vector<u64>",
        "vector<u64>",
        "u64"
      ],
      "return": [
        "0x1::option::Option<u64>",
        "0x1::option::Option<u64>"
      ]
    },
    {
      "name": "get_health_metrics",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "bool"
      ],
      "return": [
        "0x1::option::Option<u64>",
        "0x1::option::Option<u64>"
      ]
    },
    {
      "name": "get_lp_shares_and_deposited_amount",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u64",
        "address"
      ],
      "return": [
        "u64",
        "u64",
        "u64",
        "u64",
        "u64"
      ]
    },
    {
      "name": "get_min_asset_required",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "get_prices",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
      ],
      "return": [
        "vector<u64>"
      ]
    },
    {
      "name": "get_tiered_oracle_price",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "get_unhealthy_credit_accounts",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "vector<address>"
      ],
      "return": [
        "vector<address>",
        "vector<address>"
      ]
    }
  ],
  "structs": []
} as const;
