// This file is auto-generated by the generate-abis.ts script
export const moarStrategies_router_abi = {
  "address": "0x0",
  "name": "router",
  "friends": [],
  "exposed_functions": [
    {
      "name": "initialize",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "address"
      ],
      "return": []
    },
    {
      "name": "is_initialized",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "bool"
      ]
    },
    {
      "name": "claim_rewards",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "&signer",
        "vector<u8>",
        "vector<0x1::copyable_any::Any>"
      ],
      "return": [
        "vector<0x1::fungible_asset::FungibleAsset>"
      ]
    },
    {
      "name": "execute_strategy",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "&signer",
        "u8",
        "u8",
        "0x1::copyable_any::Any"
      ],
      "return": [
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>",
        "0x1::option::Option<u8>",
        "address"
      ]
    },
    {
      "name": "get_pending_rewards",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address",
        "vector<u8>"
      ],
      "return": [
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>",
        "vector<u64>"
      ]
    },
    {
      "name": "get_custom_token_price",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "get_non_fa_assets",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address",
        "u8"
      ],
      "return": [
        "vector<0x538578d562e20150569addf6a935c33330d1e62af2ae8cea0c372805e29cfba9::assets::NonFAAsset>"
      ]
    },
    {
      "name": "liquidate_non_fa_position",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "&signer",
        "&signer",
        "vector<u8>",
        "vector<0x1::copyable_any::Any>",
        "bool"
      ],
      "return": [
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
      ]
    },
    {
      "name": "preview_liquidate_non_fa_position",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address",
        "vector<u8>"
      ],
      "return": [
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>",
        "vector<u64>"
      ]
    },
    {
      "name": "set_moar_package_manager",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "address"
      ],
      "return": []
    }
  ],
  "structs": [
    {
      "name": "RouterConfig",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "key"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "moar_package_manager",
          "type": "address"
        }
      ]
    }
  ]
} as const;
