// This file is auto-generated by the generate-abis.ts script
export const moar_credit_manager_abi = {
  "address": "0x0",
  "name": "credit_manager",
  "friends": [],
  "exposed_functions": [
    {
      "name": "initialize",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer"
      ],
      "return": []
    },
    {
      "name": "is_initialized",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "bool"
      ]
    },
    {
      "name": "claim_rewards",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        }
      ],
      "params": [
        "address",
        "vector<0x1::copyable_any::Any>"
      ],
      "return": []
    },
    {
      "name": "preview_liquidate_non_fa_position",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "vector<0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::utils::AssetData>"
      ]
    },
    {
      "name": "repay",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "address",
        "u64",
        "0x1::option::Option<u64>"
      ],
      "return": []
    },
    {
      "name": "is_bad_debt",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "bool"
      ]
    },
    {
      "name": "is_position_healthy",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "bool"
      ]
    },
    {
      "name": "backfill_accountant",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "address",
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>",
        "vector<u64>",
        "u128",
        "bool",
        "u64",
        "vector<u64>",
        "vector<u64>",
        "vector<u64>"
      ],
      "return": []
    },
    {
      "name": "get_net_asset_value_and_unrealized_pnl",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "u64",
        "u128",
        "bool"
      ]
    },
    {
      "name": "get_total_pnl",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "u128",
        "bool"
      ]
    },
    {
      "name": "add_allowed_asset",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": []
    },
    {
      "name": "add_allowed_collateral_asset",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": []
    },
    {
      "name": "bad_debt_liquidation_end",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::credit_manager::LiquidationReceipt",
        "vector<0x1::fungible_asset::FungibleAsset>"
      ],
      "return": []
    },
    {
      "name": "bad_debt_liquidation_start",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "address",
        "vector<0x1::option::Option<u64>>",
        "vector<0x1::copyable_any::Any>",
        "vector<0x1::copyable_any::Any>"
      ],
      "return": [
        "vector<0x1::fungible_asset::FungibleAsset>",
        "0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::credit_manager::LiquidationReceipt"
      ]
    },
    {
      "name": "borrow_entry",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "address",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "close_credit_account",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "address"
      ],
      "return": []
    },
    {
      "name": "create_account_and_execute_actions",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": [
            "copy",
            "drop",
            "store"
          ]
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "vector<T0>"
      ],
      "return": []
    },
    {
      "name": "create_action_data",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "u8",
        "0x1::copyable_any::Any"
      ],
      "return": [
        "0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::credit_manager::ActionData"
      ]
    },
    {
      "name": "create_asset_data_public",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "address",
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>",
        "vector<0x1::option::Option<u64>>"
      ],
      "return": [
        "vector<0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::utils::AssetData>"
      ]
    },
    {
      "name": "create_credit_account",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer"
      ],
      "return": [
        "address"
      ]
    },
    {
      "name": "create_debt_data_public",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "address",
        "vector<u64>",
        "vector<0x1::option::Option<u64>>"
      ],
      "return": [
        "vector<0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::utils::DebtData>"
      ]
    },
    {
      "name": "deposit_collateral_entry",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "address",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64"
      ],
      "return": []
    },
    {
      "name": "execute_actions",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": [
            "copy",
            "drop",
            "store"
          ]
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "address",
        "vector<T0>"
      ],
      "return": []
    },
    {
      "name": "execute_strategy_public",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "address",
        "u8",
        "u8",
        "0x1::copyable_any::Any"
      ],
      "return": []
    },
    {
      "name": "get_all_credit_accounts",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "vector<address>"
      ]
    },
    {
      "name": "get_all_users",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "vector<address>"
      ]
    },
    {
      "name": "get_allowed_assets",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
      ]
    },
    {
      "name": "get_allowed_collateral_assets",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
      ]
    },
    {
      "name": "get_credit_account_debt_pools_and_assets",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "vector<u64>",
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
      ]
    },
    {
      "name": "get_credit_account_strategies",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "vector<0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::strategy::Strategy>"
      ]
    },
    {
      "name": "get_health_summary",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "bool",
        "bool",
        "u64"
      ]
    },
    {
      "name": "get_last_reward_claim_time",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "get_user_active_credit_accounts",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "vector<address>"
      ]
    },
    {
      "name": "get_user_credit_accounts",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "vector<address>"
      ]
    },
    {
      "name": "liquidation_end",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::credit_manager::LiquidationReceipt",
        "vector<0x1::fungible_asset::FungibleAsset>"
      ],
      "return": []
    },
    {
      "name": "liquidation_start",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "address",
        "vector<0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::utils::DebtData>",
        "vector<0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::utils::AssetData>",
        "vector<0x1::copyable_any::Any>",
        "vector<0x1::copyable_any::Any>"
      ],
      "return": [
        "vector<0x1::fungible_asset::FungibleAsset>",
        "0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::credit_manager::LiquidationReceipt"
      ]
    },
    {
      "name": "new_borrow_action_data",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "u64",
        "u64"
      ],
      "return": [
        "0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::credit_manager::ActionData"
      ]
    },
    {
      "name": "new_close_account_action_data",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [],
      "return": [
        "0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::credit_manager::ActionData"
      ]
    },
    {
      "name": "new_deposit_action_data",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64"
      ],
      "return": [
        "0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::credit_manager::ActionData"
      ]
    },
    {
      "name": "new_exec_strategy_action_data",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "u8",
        "u8",
        "0x1::copyable_any::Any"
      ],
      "return": [
        "0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::credit_manager::ActionData"
      ]
    },
    {
      "name": "new_repay_action_data",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "u64",
        "0x1::option::Option<u64>"
      ],
      "return": [
        "0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::credit_manager::ActionData"
      ]
    },
    {
      "name": "new_withdraw_action_data",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "address",
        "0x1::option::Option<u64>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": [
        "0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::credit_manager::ActionData"
      ]
    },
    {
      "name": "remove_allowed_asset",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": []
    },
    {
      "name": "remove_allowed_collateral_asset",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": []
    },
    {
      "name": "remove_whitelisted_liquidator",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "address"
      ],
      "return": []
    },
    {
      "name": "set_credit_manager_pause_status",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "bool"
      ],
      "return": []
    },
    {
      "name": "set_liquidation_fee",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::option::Option<u64>",
        "0x1::option::Option<u64>"
      ],
      "return": []
    },
    {
      "name": "set_max_assets",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64"
      ],
      "return": []
    },
    {
      "name": "set_max_debt_pools",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64"
      ],
      "return": []
    },
    {
      "name": "whitelist_liquidator",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "address"
      ],
      "return": []
    },
    {
      "name": "withdraw_entry",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "address",
        "address",
        "0x1::option::Option<u64>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": []
    }
  ],
  "structs": [
    {
      "name": "TokenData",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "asset",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        }
      ]
    },
    {
      "name": "RewardsClaimed",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "user",
          "type": "address"
        },
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "reward_tokens",
          "type": "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
        },
        {
          "name": "reward_amounts",
          "type": "vector<u64>"
        },
        {
          "name": "calldatas",
          "type": "vector<0x1::copyable_any::Any>"
        }
      ]
    },
    {
      "name": "Borrowed",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "user",
          "type": "address"
        },
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "pool_id",
          "type": "u64"
        },
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "Repaid",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "user",
          "type": "address"
        },
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "pool_id",
          "type": "u64"
        },
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "ActionData",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "op_type",
          "type": "u8"
        },
        {
          "name": "data",
          "type": "0x1::copyable_any::Any"
        }
      ]
    },
    {
      "name": "AllowedAssetAdded",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "asset",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        }
      ]
    },
    {
      "name": "AllowedAssetRemoved",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "asset",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        }
      ]
    },
    {
      "name": "AllowedCollateralAssetAdded",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "asset",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        }
      ]
    },
    {
      "name": "AllowedCollateralAssetRemoved",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "asset",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        }
      ]
    },
    {
      "name": "AssetAdded",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "user",
          "type": "address"
        },
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "asset",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        }
      ]
    },
    {
      "name": "AssetRemoved",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "user",
          "type": "address"
        },
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "asset",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        }
      ]
    },
    {
      "name": "AssetWithdrawn",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "user",
          "type": "address"
        },
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "receiver",
          "type": "address"
        },
        {
          "name": "amount",
          "type": "u64"
        },
        {
          "name": "asset",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        }
      ]
    },
    {
      "name": "BadDebtLiquidationEnded",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "liquidator",
          "type": "address"
        },
        {
          "name": "debt_data",
          "type": "vector<0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::utils::DebtData>"
        }
      ]
    },
    {
      "name": "BadDebtLiquidationStarted",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "liquidator",
          "type": "address"
        },
        {
          "name": "debt_data",
          "type": "vector<0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::utils::DebtData>"
        },
        {
          "name": "asset_data",
          "type": "vector<0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::utils::AssetData>"
        },
        {
          "name": "debt_repaid_value",
          "type": "u64"
        },
        {
          "name": "asset_seized_value",
          "type": "u64"
        },
        {
          "name": "bad_debt_value",
          "type": "u64"
        },
        {
          "name": "fee_assets",
          "type": "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
        },
        {
          "name": "fee_amounts",
          "type": "vector<u64>"
        }
      ]
    },
    {
      "name": "BorrowData",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "u64"
        },
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "CollateralDeposited",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "user",
          "type": "address"
        },
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "asset",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "CreditAccount",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "key"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "assets",
          "type": "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
        },
        {
          "name": "strategies",
          "type": "vector<0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::strategy::Strategy>"
        },
        {
          "name": "debt_pools",
          "type": "vector<u64>"
        },
        {
          "name": "owner",
          "type": "address"
        },
        {
          "name": "signer_cap",
          "type": "0x1::account::SignerCapability"
        },
        {
          "name": "is_active",
          "type": "bool"
        },
        {
          "name": "last_reward_claim_time",
          "type": "u64"
        },
        {
          "name": "liquidators",
          "type": "vector<address>"
        }
      ]
    },
    {
      "name": "CreditAccountClosed",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "user",
          "type": "address"
        },
        {
          "name": "credit_account_address",
          "type": "address"
        }
      ]
    },
    {
      "name": "CreditAccountCreated",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "user",
          "type": "address"
        },
        {
          "name": "credit_account_address",
          "type": "address"
        }
      ]
    },
    {
      "name": "CreditManagerConfig",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "key"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "credit_accounts",
          "type": "0x1::smart_table::SmartTable<address, 0x1::smart_vector::SmartVector<address>>"
        },
        {
          "name": "allowed_assets",
          "type": "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
        },
        {
          "name": "allowed_collateral_assets",
          "type": "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
        },
        {
          "name": "whitelisted_liquidators",
          "type": "vector<address>"
        },
        {
          "name": "liquidation_fee_bps",
          "type": "u64"
        },
        {
          "name": "bad_debt_liquidation_fee_bps",
          "type": "u64"
        },
        {
          "name": "max_debt_pools",
          "type": "u64"
        },
        {
          "name": "max_assets",
          "type": "u64"
        },
        {
          "name": "is_paused",
          "type": "bool"
        }
      ]
    },
    {
      "name": "CreditManagerPauseStatusUpdated",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "is_paused",
          "type": "bool"
        }
      ]
    },
    {
      "name": "DepositData",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "metadata",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "ExecStrategyData",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "adapter_id",
          "type": "u8"
        },
        {
          "name": "strategy",
          "type": "u8"
        },
        {
          "name": "calldata",
          "type": "0x1::copyable_any::Any"
        }
      ]
    },
    {
      "name": "LiquidationEnded",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "liquidator",
          "type": "address"
        },
        {
          "name": "debt_data",
          "type": "vector<0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::utils::DebtData>"
        },
        {
          "name": "final_health_factor",
          "type": "u64"
        },
        {
          "name": "initial_health_factor",
          "type": "u64"
        }
      ]
    },
    {
      "name": "LiquidationFeeUpdated",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "liquidation_fee_bps",
          "type": "u64"
        },
        {
          "name": "bad_debt_liquidation_fee_bps",
          "type": "u64"
        }
      ]
    },
    {
      "name": "LiquidationReceipt",
      "is_native": false,
      "is_event": false,
      "abilities": [],
      "generic_type_params": [],
      "fields": [
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "debt_data",
          "type": "vector<0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::utils::DebtData>"
        },
        {
          "name": "initial_health_factor",
          "type": "u64"
        },
        {
          "name": "is_bad_debt",
          "type": "bool"
        }
      ]
    },
    {
      "name": "LiquidationStarted",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "liquidator",
          "type": "address"
        },
        {
          "name": "debt_data",
          "type": "vector<0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::utils::DebtData>"
        },
        {
          "name": "asset_data",
          "type": "vector<0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::utils::AssetData>"
        },
        {
          "name": "debt_repaid_value",
          "type": "u64"
        },
        {
          "name": "asset_seized_value",
          "type": "u64"
        },
        {
          "name": "fee_assets",
          "type": "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
        },
        {
          "name": "fee_amounts",
          "type": "vector<u64>"
        }
      ]
    },
    {
      "name": "LiquidatorRemoved",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "liquidator",
          "type": "address"
        }
      ]
    },
    {
      "name": "LiquidatorWhitelisted",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "liquidator",
          "type": "address"
        }
      ]
    },
    {
      "name": "MaxAssetsUpdated",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "max_assets",
          "type": "u64"
        }
      ]
    },
    {
      "name": "MaxDebtPoolsUpdated",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "max_debt_pools",
          "type": "u64"
        }
      ]
    },
    {
      "name": "RepayData",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "u64"
        },
        {
          "name": "amount",
          "type": "0x1::option::Option<u64>"
        }
      ]
    },
    {
      "name": "StrategyExecuted",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "user",
          "type": "address"
        },
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "adapter_id",
          "type": "u8"
        },
        {
          "name": "strategy",
          "type": "u8"
        },
        {
          "name": "calldata",
          "type": "0x1::copyable_any::Any"
        }
      ]
    },
    {
      "name": "UnstakedByLiquidator",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "liquidator",
          "type": "address"
        },
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "adapter_id",
          "type": "u8"
        },
        {
          "name": "fa_amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "WithdrawData",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "receiver",
          "type": "address"
        },
        {
          "name": "amount",
          "type": "0x1::option::Option<u64>"
        },
        {
          "name": "asset",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        }
      ]
    }
  ]
} as const;
