// This file is auto-generated by the generate-abis.ts script
export const moar_authority_abi = {
  "address": "0x0",
  "name": "authority",
  "friends": [
    "0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::credit_manager"
  ],
  "exposed_functions": [
    {
      "name": "add_authority",
      "visibility": "friend",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "address",
        "vector<u8>"
      ],
      "return": []
    },
    {
      "name": "is_authorized",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address",
        "address",
        "u8"
      ],
      "return": [
        "bool"
      ]
    },
    {
      "name": "remove_authority",
      "visibility": "friend",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "address"
      ],
      "return": []
    },
    {
      "name": "validate_authority",
      "visibility": "friend",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "address",
        "address",
        "u8"
      ],
      "return": []
    }
  ],
  "structs": [
    {
      "name": "Authority",
      "is_native": false,
      "is_event": false,
      "is_enum": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "authorized_address",
          "type": "address"
        },
        {
          "name": "actions",
          "type": "vector<u8>"
        }
      ]
    },
    {
      "name": "AuthorityAdded",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "authorized_address",
          "type": "address"
        },
        {
          "name": "actions",
          "type": "vector<u8>"
        }
      ]
    },
    {
      "name": "AuthorityRemoved",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "authorized_address",
          "type": "address"
        }
      ]
    },
    {
      "name": "CreditAccountAuthority",
      "is_native": false,
      "is_event": false,
      "is_enum": false,
      "abilities": [
        "key"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "authorities",
          "type": "vector<0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::authority::Authority>"
        }
      ]
    }
  ]
} as const;
