// This file is auto-generated by the generate-abis.ts script
export const moar_tapp_lens_abi = {
  "address": "0x0",
  "name": "tapp_lens",
  "friends": [],
  "exposed_functions": [
    {
      "name": "get_position_info",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "vector<0xe7be11f45427d77dbe292dae5f4ec645c94ffc2cb1d861c204af6498dc779eb8::tapp_lens::PositionInfo>"
      ]
    }
  ],
  "structs": [
    {
      "name": "PendingReward",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "reward_token",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "reward_amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "PositionInfo",
      "is_native": false,
      "is_event": false,
      "abilities": [],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_address",
          "type": "address"
        },
        {
          "name": "position_address",
          "type": "address"
        },
        {
          "name": "position_index",
          "type": "u64"
        },
        {
          "name": "position_shares",
          "type": "u256"
        },
        {
          "name": "token_metadata",
          "type": "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
        },
        {
          "name": "token_amounts",
          "type": "vector<u256>"
        },
        {
          "name": "value",
          "type": "u64"
        },
        {
          "name": "pending_rewards",
          "type": "vector<0xe7be11f45427d77dbe292dae5f4ec645c94ffc2cb1d861c204af6498dc779eb8::tapp_lens::PendingReward>"
        }
      ]
    }
  ]
} as const;
