// This file is auto-generated by the generate-abis.ts script
export const moar_pool_abi = {
  "address": "0x0",
  "name": "pool",
  "friends": [
    "0xa49c8041dba4fe49fbdbb3c193c499548be9dfec1649165c8558a7bced520b5a::credit_manager"
  ],
  "exposed_functions": [
    {
      "name": "borrow",
      "visibility": "friend",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "u64",
        "address",
        "u64"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "initialize",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "address",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "deposit",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "address",
        "u64",
        "0x1::fungible_asset::FungibleAsset"
      ],
      "return": []
    },
    {
      "name": "withdraw",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64",
        "0x1::option::Option<u64>",
        "address"
      ],
      "return": []
    },
    {
      "name": "is_initialized",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "bool"
      ]
    },
    {
      "name": "create_pool",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::string::String",
        "0x1::string::String",
        "0x1::string::String",
        "0x1::string::String",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u128",
        "u128"
      ],
      "return": []
    },
    {
      "name": "lp_token_supply",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u64"
      ],
      "return": [
        "u128"
      ]
    },
    {
      "name": "get_interest_rate",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u64"
      ],
      "return": [
        "u64",
        "u64"
      ]
    },
    {
      "name": "accrue",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "u64"
      ],
      "return": []
    },
    {
      "name": "compensate_bad_debt",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "convert_amount_to_lp_shares",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u64",
        "u64"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "convert_lp_shares_to_amount",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u64",
        "u64"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "deposit_entry",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "u64",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "address"
      ],
      "return": []
    },
    {
      "name": "deposit_fa",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64",
        "0x1::fungible_asset::FungibleAsset"
      ],
      "return": []
    },
    {
      "name": "get_all_pools",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "vector<0xa49c8041dba4fe49fbdbb3c193c499548be9dfec1649165c8558a7bced520b5a::pool::PoolView>"
      ]
    },
    {
      "name": "get_borrows_of",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u64",
        "address"
      ],
      "return": [
        "u64",
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ]
    },
    {
      "name": "get_farming_pool_apy",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u64",
        "0x1::string::String"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "get_fee_recipient",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "address"
      ]
    },
    {
      "name": "get_lp_token_price",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u64"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "get_pool_asset",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u64"
      ],
      "return": [
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ]
    },
    {
      "name": "get_pool_by_id",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u64"
      ],
      "return": [
        "0x1::object::Object<0xa49c8041dba4fe49fbdbb3c193c499548be9dfec1649165c8558a7bced520b5a::pool::Pool>"
      ]
    },
    {
      "name": "get_unbonding_info",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address",
        "u64"
      ],
      "return": [
        "u64",
        "u64",
        "u64"
      ]
    },
    {
      "name": "mutate_lp_token_metadata",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64",
        "0x1::option::Option<0x1::string::String>",
        "0x1::option::Option<0x1::string::String>",
        "0x1::option::Option<u8>",
        "0x1::option::Option<0x1::string::String>",
        "0x1::option::Option<0x1::string::String>"
      ],
      "return": []
    },
    {
      "name": "pause_pool",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64"
      ],
      "return": []
    },
    {
      "name": "pool_reserve",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u64"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "pool_total_borrows",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u64"
      ],
      "return": [
        "u128"
      ]
    },
    {
      "name": "pool_total_deposited",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u64"
      ],
      "return": [
        "u128"
      ]
    },
    {
      "name": "rebalance_bad_debt",
      "visibility": "friend",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "u64",
        "address"
      ],
      "return": []
    },
    {
      "name": "repay",
      "visibility": "friend",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "u64",
        "address",
        "0x1::fungible_asset::FungibleAsset",
        "bool"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "set_borrow_cap",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64",
        "u128"
      ],
      "return": []
    },
    {
      "name": "set_deposit_cap",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64",
        "u128"
      ],
      "return": []
    },
    {
      "name": "set_fee_on_interest_bps",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "set_fee_recipient",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "address"
      ],
      "return": []
    },
    {
      "name": "set_min_amounts",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "set_origination_fee_bps",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "set_pool_name",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64",
        "0x1::string::String"
      ],
      "return": []
    },
    {
      "name": "set_pool_owner",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64",
        "address"
      ],
      "return": []
    },
    {
      "name": "set_unbonding_params",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "simulate_accrue_public",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u64"
      ],
      "return": [
        "u64",
        "u64"
      ]
    },
    {
      "name": "start_unbonding",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64",
        "0x1::option::Option<u64>"
      ],
      "return": []
    },
    {
      "name": "total_number_of_pools",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "u64"
      ]
    },
    {
      "name": "unpause_pool",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64"
      ],
      "return": []
    }
  ],
  "structs": [
    {
      "name": "Pool",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "key"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "name",
          "type": "0x1::string::String"
        },
        {
          "name": "underlying_asset",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "borrow_shares_map",
          "type": "0x1::smart_table::SmartTable<address, u64>"
        },
        {
          "name": "lp_token_refs",
          "type": "0xa49c8041dba4fe49fbdbb3c193c499548be9dfec1649165c8558a7bced520b5a::pool::LPTokenRefs"
        },
        {
          "name": "deposit_cap",
          "type": "u128"
        },
        {
          "name": "borrow_cap",
          "type": "u128"
        },
        {
          "name": "fee_on_interest_bps",
          "type": "u64"
        },
        {
          "name": "origination_fee_bps",
          "type": "u64"
        },
        {
          "name": "is_paused",
          "type": "bool"
        },
        {
          "name": "total_borrows",
          "type": "u128"
        },
        {
          "name": "total_borrow_shares",
          "type": "u128"
        },
        {
          "name": "total_deposited",
          "type": "u128"
        },
        {
          "name": "pool_owner",
          "type": "address"
        },
        {
          "name": "extend_ref",
          "type": "0x1::object::ExtendRef"
        },
        {
          "name": "withdraw_period",
          "type": "u64"
        },
        {
          "name": "unbond_period",
          "type": "u64"
        }
      ]
    },
    {
      "name": "LPTokenRefs",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "burn_ref",
          "type": "0x1::fungible_asset::BurnRef"
        },
        {
          "name": "mint_ref",
          "type": "0x1::fungible_asset::MintRef"
        },
        {
          "name": "transfer_ref",
          "type": "0x1::fungible_asset::TransferRef"
        },
        {
          "name": "mutate_metadata_ref",
          "type": "0x1::fungible_asset::MutateMetadataRef"
        }
      ]
    },
    {
      "name": "BadDebtCompensated",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "u64"
        },
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "BadDebtRebalanced",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "u64"
        },
        {
          "name": "credit_account",
          "type": "address"
        },
        {
          "name": "borrow_shares_burnt",
          "type": "u64"
        },
        {
          "name": "bad_debt_amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "BorrowCapUpdated",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "u64"
        },
        {
          "name": "borrow_cap",
          "type": "u128"
        }
      ]
    },
    {
      "name": "Borrowed",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "u64"
        },
        {
          "name": "credit_account",
          "type": "address"
        },
        {
          "name": "borrow_amount",
          "type": "u64"
        },
        {
          "name": "borrow_shares",
          "type": "u64"
        },
        {
          "name": "fee",
          "type": "u64"
        }
      ]
    },
    {
      "name": "DepositCapUpdated",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "u64"
        },
        {
          "name": "deposit_cap",
          "type": "u128"
        }
      ]
    },
    {
      "name": "Deposited",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "u64"
        },
        {
          "name": "lp",
          "type": "address"
        },
        {
          "name": "amount_in",
          "type": "u64"
        },
        {
          "name": "shares_minted",
          "type": "u64"
        }
      ]
    },
    {
      "name": "FeeOnInterestUpdated",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "u64"
        },
        {
          "name": "fee_on_interest_bps",
          "type": "u64"
        }
      ]
    },
    {
      "name": "FeeRecipientUpdated",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "new_fee_recipient",
          "type": "address"
        }
      ]
    },
    {
      "name": "InterestAccrued",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "u64"
        },
        {
          "name": "interest_accrued",
          "type": "u64"
        },
        {
          "name": "fee_shares",
          "type": "u64"
        },
        {
          "name": "fee_amount",
          "type": "u64"
        },
        {
          "name": "fee_recipient",
          "type": "address"
        }
      ]
    },
    {
      "name": "LpTokenMetadataUpdated",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "u64"
        },
        {
          "name": "name",
          "type": "0x1::option::Option<0x1::string::String>"
        },
        {
          "name": "symbol",
          "type": "0x1::option::Option<0x1::string::String>"
        },
        {
          "name": "decimals",
          "type": "0x1::option::Option<u8>"
        },
        {
          "name": "icon_uri",
          "type": "0x1::option::Option<0x1::string::String>"
        },
        {
          "name": "project_uri",
          "type": "0x1::option::Option<0x1::string::String>"
        }
      ]
    },
    {
      "name": "MinAmountsUpdated",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "min_borrow_amount",
          "type": "u64"
        },
        {
          "name": "min_debt_amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "OriginationFeeUpdated",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "u64"
        },
        {
          "name": "origination_fee_bps",
          "type": "u64"
        }
      ]
    },
    {
      "name": "PoolConfigs",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "key"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "all_pools",
          "type": "0x1::smart_vector::SmartVector<0x1::object::Object<0xa49c8041dba4fe49fbdbb3c193c499548be9dfec1649165c8558a7bced520b5a::pool::Pool>>"
        },
        {
          "name": "is_paused",
          "type": "bool"
        },
        {
          "name": "fee_recipient",
          "type": "address"
        },
        {
          "name": "min_borrow_amount",
          "type": "u64"
        },
        {
          "name": "min_debt_amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "PoolCreated",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "u64"
        },
        {
          "name": "pool",
          "type": "0x1::object::Object<0xa49c8041dba4fe49fbdbb3c193c499548be9dfec1649165c8558a7bced520b5a::pool::Pool>"
        },
        {
          "name": "underlying_asset",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        }
      ]
    },
    {
      "name": "PoolNameUpdated",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "u64"
        },
        {
          "name": "name",
          "type": "0x1::string::String"
        }
      ]
    },
    {
      "name": "PoolOwnerUpdated",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "u64"
        },
        {
          "name": "new_owner",
          "type": "address"
        }
      ]
    },
    {
      "name": "PoolPaused",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "u64"
        }
      ]
    },
    {
      "name": "PoolUnpaused",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "u64"
        }
      ]
    },
    {
      "name": "PoolView",
      "is_native": false,
      "is_event": false,
      "abilities": [],
      "generic_type_params": [],
      "fields": [
        {
          "name": "name",
          "type": "0x1::string::String"
        },
        {
          "name": "underlying_asset",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "deposit_cap",
          "type": "u128"
        },
        {
          "name": "borrow_cap",
          "type": "u128"
        },
        {
          "name": "fee_on_interest_bps",
          "type": "u64"
        },
        {
          "name": "origination_fee_bps",
          "type": "u64"
        },
        {
          "name": "is_paused",
          "type": "bool"
        },
        {
          "name": "total_borrows",
          "type": "u128"
        },
        {
          "name": "total_borrow_shares",
          "type": "u128"
        },
        {
          "name": "total_deposited",
          "type": "u128"
        },
        {
          "name": "pool_owner",
          "type": "address"
        },
        {
          "name": "interest_accrued",
          "type": "u64"
        },
        {
          "name": "total_lp_token_supply",
          "type": "u128"
        },
        {
          "name": "interest_rate",
          "type": "u64"
        },
        {
          "name": "unbond_period",
          "type": "u64"
        },
        {
          "name": "withdraw_period",
          "type": "u64"
        }
      ]
    },
    {
      "name": "Repaid",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "u64"
        },
        {
          "name": "credit_account",
          "type": "address"
        },
        {
          "name": "repaid_amount",
          "type": "u64"
        },
        {
          "name": "repaid_shares",
          "type": "u64"
        },
        {
          "name": "remaining_shares",
          "type": "u64"
        },
        {
          "name": "remaining_debt",
          "type": "u64"
        }
      ]
    },
    {
      "name": "UnbondingInfo",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "shares",
          "type": "u64"
        },
        {
          "name": "unbond_time",
          "type": "u64"
        }
      ]
    },
    {
      "name": "UnbondingParamsUpdated",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "u64"
        },
        {
          "name": "withdraw_period",
          "type": "u64"
        },
        {
          "name": "unbond_period",
          "type": "u64"
        }
      ]
    },
    {
      "name": "UnbondingStarted",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "lp",
          "type": "address"
        },
        {
          "name": "pool_id",
          "type": "u64"
        },
        {
          "name": "shares",
          "type": "u64"
        },
        {
          "name": "unbond_time",
          "type": "u64"
        }
      ]
    },
    {
      "name": "UserUnbondingInfo",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "key"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "unbonding_info",
          "type": "0x1::smart_table::SmartTable<u64, 0xa49c8041dba4fe49fbdbb3c193c499548be9dfec1649165c8558a7bced520b5a::pool::UnbondingInfo>"
        }
      ]
    },
    {
      "name": "Withdrawn",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "u64"
        },
        {
          "name": "lp",
          "type": "address"
        },
        {
          "name": "amount_out",
          "type": "u64"
        },
        {
          "name": "shares_burned",
          "type": "u64"
        }
      ]
    }
  ]
} as const;
