// This file is auto-generated by the generate-abis.ts script
export const moar_risk_manager_abi = {
  "address": "0x0",
  "name": "risk_manager",
  "friends": [
    "0xa49c8041dba4fe49fbdbb3c193c499548be9dfec1649165c8558a7bced520b5a::credit_manager"
  ],
  "exposed_functions": [
    {
      "name": "initialize",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer"
      ],
      "return": []
    },
    {
      "name": "is_initialized",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "bool"
      ]
    },
    {
      "name": "get_all_ltvs",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "vector<u64>"
      ],
      "return": [
        "vector<0xa49c8041dba4fe49fbdbb3c193c499548be9dfec1649165c8558a7bced520b5a::risk_manager::PoolLtvEntries>"
      ]
    },
    {
      "name": "get_all_ltvs_for_pool",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u64"
      ],
      "return": [
        "0xa49c8041dba4fe49fbdbb3c193c499548be9dfec1649165c8558a7bced520b5a::risk_manager::PoolLtvEntries"
      ]
    },
    {
      "name": "get_asset_data",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "address",
        "&vector<0x1::object::Object<0x1::fungible_asset::Metadata>>",
        "&vector<0x538578d562e20150569addf6a935c33330d1e62af2ae8cea0c372805e29cfba9::assets::NonFAAsset>",
        "&vector<u64>"
      ],
      "return": [
        "u64",
        "vector<u64>",
        "vector<u64>"
      ]
    },
    {
      "name": "get_assets_seized_for_bad_debt",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "address",
        "&vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
      ],
      "return": [
        "u64",
        "vector<0xa49c8041dba4fe49fbdbb3c193c499548be9dfec1649165c8558a7bced520b5a::utils::AssetData>"
      ]
    },
    {
      "name": "get_debt_data",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "address",
        "vector<u64>",
        "vector<u64>"
      ],
      "return": [
        "vector<u64>",
        "vector<u64>",
        "u64"
      ]
    },
    {
      "name": "get_liquidation_discount",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "u64"
      ]
    },
    {
      "name": "get_ltv",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u64",
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "get_ltv_simple_map",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u64"
      ],
      "return": [
        "0x1::simple_map::SimpleMap<0x1::object::Object<0x1::fungible_asset::Metadata>, u64>"
      ]
    },
    {
      "name": "get_min_asset_value",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&vector<u64>",
        "&vector<0x1::object::Object<0x1::fungible_asset::Metadata>>",
        "&vector<0x538578d562e20150569addf6a935c33330d1e62af2ae8cea0c372805e29cfba9::assets::NonFAAsset>",
        "&vector<u64>",
        "&vector<u64>",
        "&vector<u64>"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "is_position_healthy",
      "visibility": "friend",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "address",
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>",
        "&vector<0xa49c8041dba4fe49fbdbb3c193c499548be9dfec1649165c8558a7bced520b5a::strategy::Strategy>",
        "vector<u64>"
      ],
      "return": [
        "bool",
        "bool",
        "u64"
      ]
    },
    {
      "name": "set_liquidation_discount",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64"
      ],
      "return": []
    },
    {
      "name": "set_ltv",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64"
      ],
      "return": []
    },
    {
      "name": "validate_bad_debt_liquidation",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "address",
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>",
        "vector<0xa49c8041dba4fe49fbdbb3c193c499548be9dfec1649165c8558a7bced520b5a::utils::DebtData>"
      ],
      "return": [
        "vector<0xa49c8041dba4fe49fbdbb3c193c499548be9dfec1649165c8558a7bced520b5a::utils::AssetData>",
        "vector<0xa49c8041dba4fe49fbdbb3c193c499548be9dfec1649165c8558a7bced520b5a::utils::DebtData>",
        "u64",
        "u64",
        "u64"
      ]
    },
    {
      "name": "validate_bad_debt_liquidation_v2",
      "visibility": "friend",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "address",
        "vector<0xa49c8041dba4fe49fbdbb3c193c499548be9dfec1649165c8558a7bced520b5a::utils::DebtData>",
        "u64"
      ],
      "return": [
        "u64",
        "u64"
      ]
    },
    {
      "name": "validate_liquidation",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "address",
        "&vector<0xa49c8041dba4fe49fbdbb3c193c499548be9dfec1649165c8558a7bced520b5a::utils::DebtData>",
        "&vector<0xa49c8041dba4fe49fbdbb3c193c499548be9dfec1649165c8558a7bced520b5a::utils::AssetData>",
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>",
        "&vector<0xa49c8041dba4fe49fbdbb3c193c499548be9dfec1649165c8558a7bced520b5a::strategy::Strategy>",
        "vector<u64>"
      ],
      "return": [
        "u64",
        "u64",
        "u64"
      ]
    }
  ],
  "structs": [
    {
      "name": "LiquidationDiscountUpdated",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "discount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "LtvUpdated",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "u64"
        },
        {
          "name": "asset",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "ltv",
          "type": "u64"
        }
      ]
    },
    {
      "name": "PoolLtvEntries",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "drop"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "u64"
        },
        {
          "name": "asset",
          "type": "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
        },
        {
          "name": "ltv",
          "type": "vector<u64>"
        }
      ]
    },
    {
      "name": "RiskManagerConfig",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "key"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "ltv_map",
          "type": "0x1::smart_table::SmartTable<u64, 0x1::smart_table::SmartTable<0x1::object::Object<0x1::fungible_asset::Metadata>, u64>>"
        },
        {
          "name": "liquidation_discount",
          "type": "u64"
        }
      ]
    }
  ]
} as const;
