// This file is auto-generated by the generate-abis.ts script
export const moar_farming_abi = {
  "address": "0x0",
  "name": "farming",
  "friends": [
    "0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::pool"
  ],
  "exposed_functions": [
    {
      "name": "initialize",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer"
      ],
      "return": []
    },
    {
      "name": "stake",
      "visibility": "friend",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::string::String",
        "u64"
      ],
      "return": []
    },
    {
      "name": "is_initialized",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "bool"
      ]
    },
    {
      "name": "claim_reward",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::string::String",
        "0x1::string::String"
      ],
      "return": [
        "0x1::fungible_asset::FungibleAsset"
      ]
    },
    {
      "name": "pool_stake_amount",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::string::String"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "user_stake_amount",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address",
        "0x1::string::String"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "add_blacklisted_accounts",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::string::String",
        "vector<address>"
      ],
      "return": []
    },
    {
      "name": "farming_identifier",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address",
        "u64"
      ],
      "return": [
        "0x1::string::String"
      ]
    },
    {
      "name": "claim_reward_entry",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::string::String",
        "0x1::string::String"
      ],
      "return": []
    },
    {
      "name": "claimable_reward_amount",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address",
        "0x1::string::String",
        "0x1::string::String"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "total_alloc_point",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::string::String"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "get_pool_apy",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::string::String",
        "0x1::string::String",
        "u64",
        "u8"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "get_user_reward_per_month",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address",
        "0x1::string::String",
        "0x1::string::String"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "init_alloc_point",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::string::String",
        "0x1::string::String",
        "u64"
      ],
      "return": []
    },
    {
      "name": "is_blacklisted",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address",
        "0x1::string::String"
      ],
      "return": [
        "bool"
      ]
    },
    {
      "name": "is_blacklisted_account",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::string::String",
        "address"
      ],
      "return": [
        "bool"
      ]
    },
    {
      "name": "is_farming_enabled",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::string::String"
      ],
      "return": [
        "bool"
      ]
    },
    {
      "name": "is_stake_initialized",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "bool"
      ]
    },
    {
      "name": "is_user_pool_exists",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address",
        "0x1::string::String"
      ],
      "return": [
        "bool"
      ]
    },
    {
      "name": "new_epoch",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::string::String",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "new_pool",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::string::String",
        "u64"
      ],
      "return": []
    },
    {
      "name": "new_reward",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::option::Option<0x1::string::String>"
      ],
      "return": []
    },
    {
      "name": "reconcile_existing_lp_staking",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer"
      ],
      "return": []
    },
    {
      "name": "reconcile_staking_if_needed",
      "visibility": "friend",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::string::String",
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": []
    },
    {
      "name": "remove_blacklisted_accounts",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::string::String",
        "vector<address>"
      ],
      "return": []
    },
    {
      "name": "reward_token_store",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::string::String"
      ],
      "return": [
        "0x1::object::Object<0x1::fungible_asset::FungibleStore>"
      ]
    },
    {
      "name": "reward_token_store_balance",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::string::String"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "time_remaining_until_incentive_end",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::string::String"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "unstake",
      "visibility": "friend",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "address",
        "0x1::string::String",
        "u64"
      ],
      "return": []
    },
    {
      "name": "update_alloc_point",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::string::String",
        "0x1::string::String",
        "u64"
      ],
      "return": []
    },
    {
      "name": "update_alloc_point_bulk",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::string::String",
        "vector<0x1::string::String>",
        "vector<u64>"
      ],
      "return": []
    }
  ],
  "structs": [
    {
      "name": "Pool",
      "is_native": false,
      "is_event": false,
      "is_enum": false,
      "abilities": [
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "farming_identifier",
          "type": "0x1::string::String"
        },
        {
          "name": "stake_amount",
          "type": "u64"
        },
        {
          "name": "rewards",
          "type": "0x1::ordered_map::OrderedMap<0x1::string::String, 0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::farming::PoolReward>"
        }
      ]
    },
    {
      "name": "Staker",
      "is_native": false,
      "is_event": false,
      "is_enum": false,
      "abilities": [
        "key"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "user_pools",
          "type": "0x1::ordered_map::OrderedMap<0x1::string::String, 0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::farming::UserPool>"
        }
      ]
    },
    {
      "name": "BlacklistedAccountsAdded",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "farming_identifier",
          "type": "0x1::string::String"
        },
        {
          "name": "accounts",
          "type": "vector<address>"
        }
      ]
    },
    {
      "name": "BlacklistedAccountsRemoved",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "farming_identifier",
          "type": "0x1::string::String"
        },
        {
          "name": "accounts",
          "type": "vector<address>"
        }
      ]
    },
    {
      "name": "FarmingConfig",
      "is_native": false,
      "is_event": false,
      "is_enum": false,
      "abilities": [
        "key"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pools",
          "type": "0x1::ordered_map::OrderedMap<0x1::string::String, 0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::farming::Pool>"
        },
        {
          "name": "rewards",
          "type": "0x1::ordered_map::OrderedMap<0x1::string::String, 0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::farming::Reward>"
        },
        {
          "name": "blacklisted_accounts",
          "type": "0x1::ordered_map::OrderedMap<0x1::string::String, vector<address>>"
        },
        {
          "name": "reward_id_to_metadata",
          "type": "0x1::ordered_map::OrderedMap<0x1::string::String, 0x1::object::Object<0x1::fungible_asset::Metadata>>"
        }
      ]
    },
    {
      "name": "FarmingPoolCreated",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "farming_identifier",
          "type": "0x1::string::String"
        }
      ]
    },
    {
      "name": "NewRewardAdded",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "reward_id",
          "type": "0x1::string::String"
        },
        {
          "name": "asset_metadata",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        }
      ]
    },
    {
      "name": "PoolAllocPointUpdated",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "farming_identifier",
          "type": "0x1::string::String"
        },
        {
          "name": "reward_id",
          "type": "0x1::string::String"
        },
        {
          "name": "prev_alloc_point",
          "type": "u64"
        },
        {
          "name": "new_alloc_point",
          "type": "u64"
        }
      ]
    },
    {
      "name": "PoolReward",
      "is_native": false,
      "is_event": false,
      "is_enum": false,
      "abilities": [
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "reward_id",
          "type": "0x1::string::String"
        },
        {
          "name": "alloc_point",
          "type": "u64"
        },
        {
          "name": "last_rewards_sec",
          "type": "u64"
        },
        {
          "name": "acc_rewards_per_share",
          "type": "u256"
        }
      ]
    },
    {
      "name": "Reward",
      "is_native": false,
      "is_event": false,
      "is_enum": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "reward_id",
          "type": "0x1::string::String"
        },
        {
          "name": "epoch_start_sec",
          "type": "u64"
        },
        {
          "name": "epoch_end_sec",
          "type": "u64"
        },
        {
          "name": "epoch_reward_per_sec",
          "type": "u64"
        },
        {
          "name": "total_alloc_point",
          "type": "u64"
        },
        {
          "name": "reward_token_store",
          "type": "0x1::object::Object<0x1::fungible_asset::FungibleStore>"
        }
      ]
    },
    {
      "name": "RewardEpochUpdated",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "reward_id",
          "type": "0x1::string::String"
        },
        {
          "name": "epoch_start_sec",
          "type": "u64"
        },
        {
          "name": "epoch_end_sec",
          "type": "u64"
        },
        {
          "name": "epoch_reward_per_sec",
          "type": "u64"
        }
      ]
    },
    {
      "name": "RewardsClaimed",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "farming_identifier",
          "type": "0x1::string::String"
        },
        {
          "name": "reward_id",
          "type": "0x1::string::String"
        },
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "Staked",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "farming_identifier",
          "type": "0x1::string::String"
        },
        {
          "name": "user",
          "type": "address"
        },
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "Unstaked",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "farming_identifier",
          "type": "0x1::string::String"
        },
        {
          "name": "user",
          "type": "address"
        },
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "UserPool",
      "is_native": false,
      "is_event": false,
      "is_enum": false,
      "abilities": [
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "farming_identifier",
          "type": "0x1::string::String"
        },
        {
          "name": "stake_amount",
          "type": "u64"
        },
        {
          "name": "rewards",
          "type": "0x1::ordered_map::OrderedMap<0x1::string::String, 0xa3afc59243afb6deeac965d40b25d509bb3aebc12f502b8592c283070abc2e07::farming::UserPoolReward>"
        }
      ]
    },
    {
      "name": "UserPoolReward",
      "is_native": false,
      "is_event": false,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "reward_id",
          "type": "0x1::string::String"
        },
        {
          "name": "last_acc_rewards_per_share",
          "type": "u256"
        },
        {
          "name": "reward_amount",
          "type": "u64"
        }
      ]
    }
  ]
} as const;
