// This file is auto-generated by the generate-abis.ts script
export const moar_hyperion_lens_abi = {
  "address": "0x0",
  "name": "hyperion_lens",
  "friends": [],
  "exposed_functions": [
    {
      "name": "get_sqrt_price_at_tick",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u32"
      ],
      "return": [
        "u128"
      ]
    },
    {
      "name": "get_tick_at_sqrt_price",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u128"
      ],
      "return": [
        "u32"
      ]
    },
    {
      "name": "max_sqrt_price",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "u128"
      ]
    },
    {
      "name": "min_sqrt_price",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "u128"
      ]
    },
    {
      "name": "get_position_info",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address",
        "address"
      ],
      "return": [
        "0xfa3d17dfdf5037ed9b68c2c85976f899155048fdf96bc77b57ef1ad206c5b007::hyperion_lens::PositionInfo"
      ]
    },
    {
      "name": "get_price_from_sqrt_price_x64",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u128",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "get_price_from_tick",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u32",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "get_price_from_tick_multi",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "vector<u32>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": [
        "vector<u64>"
      ]
    }
  ],
  "structs": [
    {
      "name": "PendingReward",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "reward_token",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "reward_amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "PositionInfo",
      "is_native": false,
      "is_event": false,
      "abilities": [],
      "generic_type_params": [],
      "fields": [
        {
          "name": "liquidity",
          "type": "u128"
        },
        {
          "name": "token_a_metadata",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_b_metadata",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_a_amount",
          "type": "u64"
        },
        {
          "name": "token_b_amount",
          "type": "u64"
        },
        {
          "name": "tick_lower",
          "type": "u32"
        },
        {
          "name": "tick_upper",
          "type": "u32"
        },
        {
          "name": "current_tick",
          "type": "u32"
        },
        {
          "name": "pending_fees",
          "type": "vector<u64>"
        },
        {
          "name": "pending_rewards",
          "type": "vector<0xfa3d17dfdf5037ed9b68c2c85976f899155048fdf96bc77b57ef1ad206c5b007::hyperion_lens::PendingReward>"
        },
        {
          "name": "tick_lower_price",
          "type": "u64"
        },
        {
          "name": "tick_upper_price",
          "type": "u64"
        },
        {
          "name": "current_price",
          "type": "u64"
        }
      ]
    }
  ]
} as const;
