// This file is auto-generated by the generate-abis.ts script
export const moar_interest_rate_model_abi = {
  "address": "0x0",
  "name": "interest_rate_model",
  "friends": [
    "0xeeaea90cd2a6a0d7a184a87a648aa43b2ffd871933f8b7d86638f584de856b7c::pool"
  ],
  "exposed_functions": [
    {
      "name": "initialize",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer"
      ],
      "return": []
    },
    {
      "name": "is_initialized",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "bool"
      ]
    },
    {
      "name": "create_piecewise_linear_model",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u64",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64"
      ],
      "return": [
        "0xeeaea90cd2a6a0d7a184a87a648aa43b2ffd871933f8b7d86638f584de856b7c::interest_rate_model::PiecewiseLinearInterestRateModel",
        "0x1::copyable_any::Any"
      ]
    },
    {
      "name": "get_interest_accrued",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "u64",
        "u128",
        "u128"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "get_interest_rate",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "u64",
        "u128",
        "u128"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "get_last_accrued_at",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u64"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "get_linear_interest_rate_at_utilization",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u64",
        "u64"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "get_piecewise_linear_model",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u64"
      ],
      "return": [
        "u64",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64"
      ]
    },
    {
      "name": "set_piecewise_linear_model",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "update_last_accrued_at",
      "visibility": "friend",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "u64"
      ],
      "return": []
    },
    {
      "name": "update_piecewise_linear_model",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    }
  ],
  "structs": [
    {
      "name": "InterestRateConfig",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "key"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "interest_rate_model",
          "type": "0x1::smart_table::SmartTable<u64, 0xeeaea90cd2a6a0d7a184a87a648aa43b2ffd871933f8b7d86638f584de856b7c::interest_rate_model::InterestRateModel>"
        }
      ]
    },
    {
      "name": "InterestRateModel",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "rate_model",
          "type": "u8"
        },
        {
          "name": "rate_data",
          "type": "0x1::copyable_any::Any"
        },
        {
          "name": "last_accrued_at",
          "type": "u64"
        }
      ]
    },
    {
      "name": "InterestRateModelAdded",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "u64"
        },
        {
          "name": "rate_model",
          "type": "u8"
        },
        {
          "name": "rate_data",
          "type": "0x1::copyable_any::Any"
        }
      ]
    },
    {
      "name": "InterestRateModelUpdated",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_id",
          "type": "u64"
        },
        {
          "name": "rate_model",
          "type": "u8"
        },
        {
          "name": "rate_data",
          "type": "0x1::copyable_any::Any"
        }
      ]
    },
    {
      "name": "PiecewiseLinearInterestRateModel",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "r1",
          "type": "u64"
        },
        {
          "name": "r2",
          "type": "u64"
        },
        {
          "name": "r3",
          "type": "u64"
        },
        {
          "name": "r4",
          "type": "u64"
        },
        {
          "name": "r5",
          "type": "u64"
        },
        {
          "name": "u2",
          "type": "u64"
        },
        {
          "name": "u3",
          "type": "u64"
        },
        {
          "name": "u4",
          "type": "u64"
        }
      ]
    }
  ]
} as const;
