// This file is auto-generated by the generate-abis.ts script
export const moarStrategies_dex_swap_adapter_abi = {
  "address": "0x0",
  "name": "dex_swap_adapter",
  "friends": [
    "0xc9613ed6276f7c70a5eabdef237dc57ea07a72f563d15cd998dc31ebe6cc0db5::router"
  ],
  "exposed_functions": [
    {
      "name": "create_hyperion_multi_pool_swap_inputs",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "vector<address>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "bool"
      ],
      "return": [
        "0xc9613ed6276f7c70a5eabdef237dc57ea07a72f563d15cd998dc31ebe6cc0db5::dex_swap_adapter::HyperionMultiPoolSwapInputs",
        "0x1::copyable_any::Any"
      ]
    },
    {
      "name": "create_hyperion_single_pool_swap_inputs",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u8",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "u128",
        "u64",
        "bool",
        "bool"
      ],
      "return": [
        "0xc9613ed6276f7c70a5eabdef237dc57ea07a72f563d15cd998dc31ebe6cc0db5::dex_swap_adapter::HyperionSinglePoolSwapInputs",
        "0x1::copyable_any::Any"
      ]
    },
    {
      "name": "create_thala_v2_swap_inputs",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x7730cd28ee1cdc9e999336cbc430f99e7c44397c0aa77516f6f23a78559bb5::pool::Pool>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "bool",
        "bool"
      ],
      "return": [
        "0xc9613ed6276f7c70a5eabdef237dc57ea07a72f563d15cd998dc31ebe6cc0db5::dex_swap_adapter::ThalaV2SwapInputs",
        "0x1::copyable_any::Any"
      ]
    },
    {
      "name": "execute_strategy",
      "visibility": "friend",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u8",
        "0x1::copyable_any::Any"
      ],
      "return": [
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>",
        "0x1::option::Option<u8>",
        "address"
      ]
    },
    {
      "name": "preview_hyperion_swap_exact_in",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "vector<address>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "preview_hyperion_swap_exact_out",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "vector<address>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "preview_thala_v2_swap",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x7730cd28ee1cdc9e999336cbc430f99e7c44397c0aa77516f6f23a78559bb5::pool::Pool>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "bool",
        "0x1::option::Option<address>"
      ],
      "return": [
        "0x7730cd28ee1cdc9e999336cbc430f99e7c44397c0aa77516f6f23a78559bb5::pool::SwapPreview"
      ]
    }
  ],
  "structs": [
    {
      "name": "SwapEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "dex_id",
          "type": "u8"
        },
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "from_token",
          "type": "address"
        },
        {
          "name": "amount_in",
          "type": "u64"
        },
        {
          "name": "to_token",
          "type": "address"
        },
        {
          "name": "amount_out",
          "type": "u64"
        },
        {
          "name": "trade_value",
          "type": "u64"
        },
        {
          "name": "is_trade",
          "type": "bool"
        }
      ]
    },
    {
      "name": "HyperionMultiPoolSwapInputs",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pools_path",
          "type": "vector<address>"
        },
        {
          "name": "from_token",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "amount_in",
          "type": "u64"
        },
        {
          "name": "to_token",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "amount_out_min",
          "type": "u64"
        },
        {
          "name": "is_trade",
          "type": "bool"
        }
      ]
    },
    {
      "name": "HyperionSinglePoolSwapInputs",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "fee_tier",
          "type": "u8"
        },
        {
          "name": "from_token",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "amount_in",
          "type": "u64"
        },
        {
          "name": "to_token",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "amount_out",
          "type": "u64"
        },
        {
          "name": "sqrt_price_limit",
          "type": "u128"
        },
        {
          "name": "deadline",
          "type": "u64"
        },
        {
          "name": "is_exact_in",
          "type": "bool"
        },
        {
          "name": "is_trade",
          "type": "bool"
        }
      ]
    },
    {
      "name": "ThalaV2SwapInputs",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_obj",
          "type": "0x1::object::Object<0x7730cd28ee1cdc9e999336cbc430f99e7c44397c0aa77516f6f23a78559bb5::pool::Pool>"
        },
        {
          "name": "from_token",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "amount_in",
          "type": "u64"
        },
        {
          "name": "to_token",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "amount_out",
          "type": "u64"
        },
        {
          "name": "is_exact_in",
          "type": "bool"
        },
        {
          "name": "is_trade",
          "type": "bool"
        }
      ]
    }
  ]
} as const;
