// This file is auto-generated by the generate-abis.ts script
export const moarTiered_tiered_oracle_abi = {
  "address": "0x0",
  "name": "tiered_oracle",
  "friends": [],
  "exposed_functions": [
    {
      "name": "asset_oracle_address",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0xd74401951a74141b1c0b2a7285fb7e060bf56be829f9e34182819f9c5546e90b::tiered_oracle::TieredOracle>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": [
        "address"
      ]
    },
    {
      "name": "get_price",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0xd74401951a74141b1c0b2a7285fb7e060bf56be829f9e34182819f9c5546e90b::tiered_oracle::TieredOracle>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": [
        "u8",
        "0x4dcae85fc5559071906cd5c76b7420fcbb4b0a92f00ab40ffc394aadbbff5ee9::fixed_point64::FixedPoint64"
      ]
    },
    {
      "name": "must_get_price",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0xd74401951a74141b1c0b2a7285fb7e060bf56be829f9e34182819f9c5546e90b::tiered_oracle::TieredOracle>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": [
        "0x4dcae85fc5559071906cd5c76b7420fcbb4b0a92f00ab40ffc394aadbbff5ee9::fixed_point64::FixedPoint64"
      ]
    },
    {
      "name": "new",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer"
      ],
      "return": [
        "0x1::object::Object<0xd74401951a74141b1c0b2a7285fb7e060bf56be829f9e34182819f9c5546e90b::tiered_oracle::TieredOracle>"
      ]
    },
    {
      "name": "register",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0xd74401951a74141b1c0b2a7285fb7e060bf56be829f9e34182819f9c5546e90b::tiered_oracle::TieredOracle>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "set_staleness_and_broken_seconds",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0xd74401951a74141b1c0b2a7285fb7e060bf56be829f9e34182819f9c5546e90b::tiered_oracle::TieredOracle>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::option::Option<u64>",
        "0x1::option::Option<u64>"
      ],
      "return": []
    },
    {
      "name": "set_tier_pyth",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0xd74401951a74141b1c0b2a7285fb7e060bf56be829f9e34182819f9c5546e90b::tiered_oracle::TieredOracle>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "bool",
        "vector<u8>"
      ],
      "return": []
    },
    {
      "name": "set_tier_switchboard",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0xd74401951a74141b1c0b2a7285fb7e060bf56be829f9e34182819f9c5546e90b::tiered_oracle::TieredOracle>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "bool",
        "address"
      ],
      "return": []
    }
  ],
  "structs": [
    {
      "name": "AssetOracle",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "extend_ref",
          "type": "0x1::object::ExtendRef"
        },
        {
          "name": "tier_1",
          "type": "u8"
        },
        {
          "name": "tier_2",
          "type": "u8"
        },
        {
          "name": "staleness_seconds",
          "type": "u64"
        },
        {
          "name": "broken_seconds",
          "type": "u64"
        }
      ]
    },
    {
      "name": "TieredOracle",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "key"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "extend_ref",
          "type": "0x1::object::ExtendRef"
        },
        {
          "name": "assets",
          "type": "0x1::smart_table::SmartTable<0x1::object::Object<0x1::fungible_asset::Metadata>, 0xd74401951a74141b1c0b2a7285fb7e060bf56be829f9e34182819f9c5546e90b::tiered_oracle::AssetOracle>"
        }
      ]
    }
  ]
} as const;
