// This file is auto-generated by the generate-abis.ts script
export const moarStrategies_tapp_adapter_abi = {
  "address": "0x0",
  "name": "tapp_adapter",
  "friends": [
    "0xc9613ed6276f7c70a5eabdef237dc57ea07a72f563d15cd998dc31ebe6cc0db5::router"
  ],
  "exposed_functions": [
    {
      "name": "initialize",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer"
      ],
      "return": []
    },
    {
      "name": "is_initialized",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "bool"
      ]
    },
    {
      "name": "collect_fee",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "address",
        "address"
      ],
      "return": []
    },
    {
      "name": "get_pending_rewards",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>",
        "vector<u64>"
      ]
    },
    {
      "name": "get_ltv_map",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "0x1::simple_map::SimpleMap<u64, u64>"
      ]
    },
    {
      "name": "execute_strategy",
      "visibility": "friend",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u8",
        "0x1::copyable_any::Any"
      ],
      "return": [
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>",
        "0x1::option::Option<u8>",
        "address"
      ]
    },
    {
      "name": "add_reward_token",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": []
    },
    {
      "name": "create_liquidate_non_fa_position_inputs",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "vector<vector<u256>>"
      ],
      "return": [
        "0xc9613ed6276f7c70a5eabdef237dc57ea07a72f563d15cd998dc31ebe6cc0db5::tapp_adapter::LiquidateNonFAPositionInputs",
        "0x1::copyable_any::Any"
      ]
    },
    {
      "name": "get_all_positions",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "vector<0xc9613ed6276f7c70a5eabdef237dc57ea07a72f563d15cd998dc31ebe6cc0db5::tapp_adapter::Position>"
      ]
    },
    {
      "name": "get_all_positions_and_pools",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "vector<address>",
        "vector<address>",
        "vector<u64>"
      ]
    },
    {
      "name": "get_combined_pool_assets",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
      ]
    },
    {
      "name": "get_non_fa_assets",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "vector<0xc9613ed6276f7c70a5eabdef237dc57ea07a72f563d15cd998dc31ebe6cc0db5::assets::NonFAAsset>"
      ]
    },
    {
      "name": "get_rewards_fee",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "liquidate_non_fa_position",
      "visibility": "friend",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::copyable_any::Any"
      ],
      "return": [
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
      ]
    },
    {
      "name": "preview_liquidate_non_fa_position",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>",
        "vector<u64>"
      ]
    },
    {
      "name": "remove_reward_token",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": []
    },
    {
      "name": "set_ltv_map",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "address",
        "vector<u64>",
        "vector<u64>"
      ],
      "return": []
    },
    {
      "name": "set_rewards_fee",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::option::Option<address>",
        "u64"
      ],
      "return": []
    },
    {
      "name": "create_add_stable_liquidity_inputs",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address",
        "0x1::option::Option<address>",
        "vector<u256>",
        "u256"
      ],
      "return": [
        "0xc9613ed6276f7c70a5eabdef237dc57ea07a72f563d15cd998dc31ebe6cc0db5::tapp_adapter::AddStableLiquidityInputs",
        "0x1::copyable_any::Any"
      ]
    },
    {
      "name": "create_remove_stable_liquidity_inputs",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address",
        "address",
        "u8",
        "0x1::option::Option<u256>",
        "0x1::option::Option<vector<u256>>",
        "0x1::option::Option<u64>",
        "0x1::option::Option<u256>"
      ],
      "return": [
        "0xc9613ed6276f7c70a5eabdef237dc57ea07a72f563d15cd998dc31ebe6cc0db5::tapp_adapter::RemoveStableLiquidityInputs",
        "0x1::copyable_any::Any"
      ]
    },
    {
      "name": "get_oracle_based_position_value",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address",
        "u64"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "get_pool_assets",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ]
    },
    {
      "name": "get_pool_assets_v2",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
      ]
    },
    {
      "name": "get_position_value",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address",
        "address",
        "u64"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "get_remove_liquidity_value",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address",
        "u64"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "set_pool_price_diff_tolerance",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u8",
        "u64"
      ],
      "return": []
    }
  ],
  "structs": [
    {
      "name": "Position",
      "is_native": false,
      "is_event": false,
      "is_enum": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool",
          "type": "address"
        },
        {
          "name": "position_address",
          "type": "address"
        },
        {
          "name": "position_idx",
          "type": "u64"
        }
      ]
    },
    {
      "name": "FeeOnRewardsCharged",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "pool_address",
          "type": "address"
        },
        {
          "name": "position_index",
          "type": "u64"
        },
        {
          "name": "metadata",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "initial_pending_amount",
          "type": "u64"
        },
        {
          "name": "current_pending_amount",
          "type": "u64"
        },
        {
          "name": "fee_on_rewards",
          "type": "u64"
        },
        {
          "name": "fee_recipient",
          "type": "address"
        }
      ]
    },
    {
      "name": "LiquidateNonFAPositionEvent",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "removed_assets_metadata",
          "type": "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
        }
      ]
    },
    {
      "name": "LiquidateNonFAPositionInputs",
      "is_native": false,
      "is_event": false,
      "is_enum": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "min_outs",
          "type": "vector<vector<u256>>"
        }
      ]
    },
    {
      "name": "LtvMapSet",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_address",
          "type": "address"
        },
        {
          "name": "ltv_map",
          "type": "0x1::simple_map::SimpleMap<u64, u64>"
        }
      ]
    },
    {
      "name": "PoolRewardsFeeSet",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_address",
          "type": "address"
        },
        {
          "name": "pool_rewards_fee",
          "type": "u64"
        }
      ]
    },
    {
      "name": "RewardTokenAdded",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "reward_token",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        }
      ]
    },
    {
      "name": "RewardTokenRemoved",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "reward_token",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        }
      ]
    },
    {
      "name": "RewardsFeeConfig",
      "is_native": false,
      "is_event": false,
      "is_enum": false,
      "abilities": [
        "key"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_rewards_fee",
          "type": "0x1::simple_map::SimpleMap<address, u64>"
        },
        {
          "name": "rewards_fee",
          "type": "u64"
        }
      ]
    },
    {
      "name": "RewardsFeeSet",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "rewards_fee",
          "type": "u64"
        }
      ]
    },
    {
      "name": "AddStableLiquidityEvent",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "pool_address",
          "type": "address"
        },
        {
          "name": "position_address",
          "type": "address"
        },
        {
          "name": "position_idx",
          "type": "u64"
        },
        {
          "name": "amounts",
          "type": "vector<u256>"
        },
        {
          "name": "min_mint_amount",
          "type": "u256"
        }
      ]
    },
    {
      "name": "AddStableLiquidityInputs",
      "is_native": false,
      "is_event": false,
      "is_enum": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_address",
          "type": "address"
        },
        {
          "name": "position_address",
          "type": "0x1::option::Option<address>"
        },
        {
          "name": "amounts",
          "type": "vector<u256>"
        },
        {
          "name": "min_mint_amount",
          "type": "u256"
        }
      ]
    },
    {
      "name": "CollectFeesEvent",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "pool_address",
          "type": "address"
        },
        {
          "name": "position_address",
          "type": "address"
        }
      ]
    },
    {
      "name": "RemoveStableLiquidityEvent",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "pool_address",
          "type": "address"
        },
        {
          "name": "position_address",
          "type": "address"
        },
        {
          "name": "mode",
          "type": "u8"
        },
        {
          "name": "lp_burn_amount",
          "type": "0x1::option::Option<u256>"
        },
        {
          "name": "amounts",
          "type": "0x1::option::Option<vector<u256>>"
        },
        {
          "name": "coin_idx",
          "type": "0x1::option::Option<u64>"
        },
        {
          "name": "min_received",
          "type": "0x1::option::Option<u256>"
        }
      ]
    },
    {
      "name": "RemoveStableLiquidityInputs",
      "is_native": false,
      "is_event": false,
      "is_enum": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_address",
          "type": "address"
        },
        {
          "name": "position_address",
          "type": "address"
        },
        {
          "name": "mode",
          "type": "u8"
        },
        {
          "name": "lp_burn_amount",
          "type": "0x1::option::Option<u256>"
        },
        {
          "name": "amounts",
          "type": "0x1::option::Option<vector<u256>>"
        },
        {
          "name": "coin_idx",
          "type": "0x1::option::Option<u64>"
        },
        {
          "name": "min_received",
          "type": "0x1::option::Option<u256>"
        }
      ]
    },
    {
      "name": "TappAdapterConfig",
      "is_native": false,
      "is_event": false,
      "is_enum": false,
      "abilities": [
        "key"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "positions",
          "type": "0x1::ordered_map::OrderedMap<address, vector<0xc9613ed6276f7c70a5eabdef237dc57ea07a72f563d15cd998dc31ebe6cc0db5::tapp_adapter::Position>>"
        },
        {
          "name": "ltv_map",
          "type": "0x1::ordered_map::OrderedMap<address, 0x1::simple_map::SimpleMap<u64, u64>>"
        },
        {
          "name": "reward_tokens",
          "type": "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
        }
      ]
    },
    {
      "name": "TappDiffTolerance",
      "is_native": false,
      "is_event": false,
      "is_enum": false,
      "abilities": [
        "key"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_price_diff_tolerance",
          "type": "0x1::simple_map::SimpleMap<u8, u64>"
        }
      ]
    },
    {
      "name": "TappDiffToleranceSet",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "hook_type",
          "type": "u8"
        },
        {
          "name": "diff_tolerance",
          "type": "u64"
        }
      ]
    }
  ]
} as const;
