// This file is auto-generated by the generate-abis.ts script
export const moarStrategies_thala_v2_adapter_abi = {
  "address": "0x0",
  "name": "thala_v2_adapter",
  "friends": [
    "0x538578d562e20150569addf6a935c33330d1e62af2ae8cea0c372805e29cfba9::router"
  ],
  "exposed_functions": [
    {
      "name": "initialize",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer"
      ],
      "return": []
    },
    {
      "name": "is_initialized",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "bool"
      ]
    },
    {
      "name": "claim_rewards",
      "visibility": "friend",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::copyable_any::Any"
      ],
      "return": [
        "vector<0x1::fungible_asset::FungibleAsset>"
      ]
    },
    {
      "name": "execute_strategy",
      "visibility": "friend",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u8",
        "0x1::copyable_any::Any"
      ],
      "return": [
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>",
        "0x1::option::Option<u8>",
        "address"
      ]
    },
    {
      "name": "create_add_liquidity_inputs",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address",
        "vector<u64>",
        "u64",
        "bool"
      ],
      "return": [
        "0x538578d562e20150569addf6a935c33330d1e62af2ae8cea0c372805e29cfba9::thala_v2_adapter::AddLiquidityInputs",
        "0x1::copyable_any::Any"
      ]
    },
    {
      "name": "create_claim_rewards_inputs",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
      ],
      "return": [
        "0x538578d562e20150569addf6a935c33330d1e62af2ae8cea0c372805e29cfba9::thala_v2_adapter::ClaimRewardInputs",
        "0x1::copyable_any::Any"
      ]
    },
    {
      "name": "create_remove_liquidity_inputs",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "vector<u64>",
        "bool"
      ],
      "return": [
        "0x538578d562e20150569addf6a935c33330d1e62af2ae8cea0c372805e29cfba9::thala_v2_adapter::RemoveLiquidityInputs",
        "0x1::copyable_any::Any"
      ]
    },
    {
      "name": "get_custom_token_price",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "add_thala_v2_pool_info",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "vector<0x1::string::String>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": []
    },
    {
      "name": "create_stake_inputs",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "u64",
        "u64"
      ],
      "return": [
        "0x538578d562e20150569addf6a935c33330d1e62af2ae8cea0c372805e29cfba9::thala_v2_adapter::StakeInputs",
        "0x1::copyable_any::Any"
      ]
    },
    {
      "name": "get_xlpt_metadata_from_lpt_metadata",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": [
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ]
    },
    {
      "name": "is_staked_lp_token",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": [
        "bool"
      ]
    },
    {
      "name": "update_thala_v2_pool_info",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "vector<0x1::string::String>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": []
    }
  ],
  "structs": [
    {
      "name": "AddLiquidityEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "pool",
          "type": "0x1::object::Object<0x7730cd28ee1cdc9e999336cbc430f99e7c44397c0aa77516f6f23a78559bb5::pool::Pool>"
        },
        {
          "name": "amounts",
          "type": "vector<u64>"
        },
        {
          "name": "pool_type",
          "type": "u8"
        },
        {
          "name": "amount_out",
          "type": "u64"
        },
        {
          "name": "is_stake",
          "type": "bool"
        }
      ]
    },
    {
      "name": "RemoveLiquidityEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "pool",
          "type": "0x1::object::Object<0x7730cd28ee1cdc9e999336cbc430f99e7c44397c0aa77516f6f23a78559bb5::pool::Pool>"
        },
        {
          "name": "lp_token_metadata",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "lp_token_amount",
          "type": "u64"
        },
        {
          "name": "amounts_out",
          "type": "vector<u64>"
        },
        {
          "name": "is_unstake",
          "type": "bool"
        }
      ]
    },
    {
      "name": "AddLiquidityInputs",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_address",
          "type": "address"
        },
        {
          "name": "amounts",
          "type": "vector<u64>"
        },
        {
          "name": "min_out",
          "type": "u64"
        },
        {
          "name": "is_stake",
          "type": "bool"
        }
      ]
    },
    {
      "name": "RemoveLiquidityInputs",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_address",
          "type": "address"
        },
        {
          "name": "lp_token_metadata",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "amount",
          "type": "u64"
        },
        {
          "name": "min_out_amounts",
          "type": "vector<u64>"
        },
        {
          "name": "is_unstake",
          "type": "bool"
        }
      ]
    },
    {
      "name": "ClaimRewardInputs",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "lpt_metadatas",
          "type": "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
        }
      ]
    },
    {
      "name": "PoolInfo",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "xlpt_reward_ids",
          "type": "vector<0x1::string::String>"
        },
        {
          "name": "xlpt_metadata",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        }
      ]
    },
    {
      "name": "PoolLookup",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "key"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "lp_token_metadata_to_pool_info",
          "type": "0x1::smart_table::SmartTable<0x1::object::Object<0x1::fungible_asset::Metadata>, 0x538578d562e20150569addf6a935c33330d1e62af2ae8cea0c372805e29cfba9::thala_v2_adapter::PoolInfo>"
        }
      ]
    },
    {
      "name": "PoolLookupAdded",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "lp_token_metadata",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "xlpt_reward_ids",
          "type": "vector<0x1::string::String>"
        },
        {
          "name": "xlpt_metadata",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        }
      ]
    },
    {
      "name": "PoolLookupUpdated",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "lp_token_metadata",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "xlpt_reward_ids",
          "type": "vector<0x1::string::String>"
        },
        {
          "name": "xlpt_metadata",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        }
      ]
    },
    {
      "name": "StakeAPTAndThAPTEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "apt_amount",
          "type": "u64"
        },
        {
          "name": "thapt_amount",
          "type": "u64"
        },
        {
          "name": "sthapt_amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "StakeAPTEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "apt_amount",
          "type": "u64"
        },
        {
          "name": "thapt_amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "StakeInputs",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "input_amount",
          "type": "u64"
        },
        {
          "name": "min_out_amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "StakeThAPTEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "thapt_amount",
          "type": "u64"
        },
        {
          "name": "sthapt_amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "UnstakeThAPTEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "sthapt_amount",
          "type": "u64"
        },
        {
          "name": "thapt_amount",
          "type": "u64"
        }
      ]
    }
  ]
} as const;
