// This file is auto-generated by the generate-abis.ts script
export const moarStrategies_hyperion_adapter_abi = {
  "address": "0x0",
  "name": "hyperion_adapter",
  "friends": [
    "0xc9613ed6276f7c70a5eabdef237dc57ea07a72f563d15cd998dc31ebe6cc0db5::router"
  ],
  "exposed_functions": [
    {
      "name": "initialize",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer"
      ],
      "return": []
    },
    {
      "name": "is_initialized",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "bool"
      ]
    },
    {
      "name": "claim_rewards",
      "visibility": "friend",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::copyable_any::Any"
      ],
      "return": [
        "vector<0x1::fungible_asset::FungibleAsset>"
      ]
    },
    {
      "name": "get_pending_rewards",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>",
        "vector<u64>"
      ]
    },
    {
      "name": "get_ltv_map",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "0x1::simple_map::SimpleMap<u64, u64>"
      ]
    },
    {
      "name": "execute_strategy",
      "visibility": "friend",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u8",
        "0x1::copyable_any::Any"
      ],
      "return": [
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>",
        "0x1::option::Option<u8>",
        "address"
      ]
    },
    {
      "name": "add_reward_token",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": []
    },
    {
      "name": "create_add_liquidity_inputs",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::option::Option<0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::option::Option<u32>",
        "0x1::option::Option<u32>",
        "u8",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64",
        "bool"
      ],
      "return": [
        "0xc9613ed6276f7c70a5eabdef237dc57ea07a72f563d15cd998dc31ebe6cc0db5::hyperion_adapter::AddLiquidityInputs",
        "0x1::copyable_any::Any"
      ]
    },
    {
      "name": "create_add_liquidity_optimally_inputs",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::option::Option<0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::option::Option<u32>",
        "0x1::option::Option<u32>",
        "u8",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64",
        "bool",
        "u64"
      ],
      "return": [
        "0xc9613ed6276f7c70a5eabdef237dc57ea07a72f563d15cd998dc31ebe6cc0db5::hyperion_adapter::AddLiquidityOptimallyInputs",
        "0x1::copyable_any::Any"
      ]
    },
    {
      "name": "create_claim_rewards_inputs",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "u8",
        "0x1::copyable_any::Any"
      ]
    },
    {
      "name": "create_liquidate_non_fa_position_inputs",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "vector<u64>",
        "vector<u64>"
      ],
      "return": [
        "vector<0xc9613ed6276f7c70a5eabdef237dc57ea07a72f563d15cd998dc31ebe6cc0db5::hyperion_adapter::LiquidateNonFAPositionInputs>",
        "0x1::copyable_any::Any"
      ]
    },
    {
      "name": "create_rebalance_inputs",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8",
        "u64",
        "u64",
        "u32",
        "u32",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64",
        "bool",
        "u64"
      ],
      "return": [
        "0xc9613ed6276f7c70a5eabdef237dc57ea07a72f563d15cd998dc31ebe6cc0db5::hyperion_adapter::RebalanceInputs",
        "0x1::copyable_any::Any"
      ]
    },
    {
      "name": "create_remove_liquidity_inputs",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>",
        "u128",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u8",
        "u64",
        "u64",
        "bool"
      ],
      "return": [
        "0xc9613ed6276f7c70a5eabdef237dc57ea07a72f563d15cd998dc31ebe6cc0db5::hyperion_adapter::RemoveLiquidityInputs",
        "0x1::copyable_any::Any"
      ]
    },
    {
      "name": "get_all_positions",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "vector<0xc9613ed6276f7c70a5eabdef237dc57ea07a72f563d15cd998dc31ebe6cc0db5::hyperion_adapter::Position>"
      ]
    },
    {
      "name": "get_all_positions_and_pools",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "vector<address>",
        "vector<address>"
      ]
    },
    {
      "name": "get_clamm_position_value",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "get_clamm_position_value_from_tick_and_liquidity",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address",
        "u32",
        "u32",
        "u128",
        "vector<u64>"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "get_custom_token_price",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": [
        "u64"
      ]
    },
    {
      "name": "get_non_fa_assets",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "vector<0xc9613ed6276f7c70a5eabdef237dc57ea07a72f563d15cd998dc31ebe6cc0db5::assets::NonFAAsset>"
      ]
    },
    {
      "name": "get_oracle_sqrt_price",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": [
        "u128"
      ]
    },
    {
      "name": "get_reward_tokens",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
      ]
    },
    {
      "name": "liquidate_non_fa_position",
      "visibility": "friend",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "&signer",
        "0x1::copyable_any::Any"
      ],
      "return": [
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
      ]
    },
    {
      "name": "preview_liquidate_non_fa_position",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>",
        "vector<u64>"
      ]
    },
    {
      "name": "remove_reward_token",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x1::fungible_asset::Metadata>"
      ],
      "return": []
    },
    {
      "name": "set_ltv_map",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>",
        "vector<u64>",
        "vector<u64>"
      ],
      "return": []
    }
  ],
  "structs": [
    {
      "name": "Position",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool",
          "type": "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>"
        },
        {
          "name": "position_object",
          "type": "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>"
        }
      ]
    },
    {
      "name": "AddLiquidityEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "pool",
          "type": "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>"
        },
        {
          "name": "position_object",
          "type": "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>"
        },
        {
          "name": "is_stake",
          "type": "bool"
        }
      ]
    },
    {
      "name": "RemoveLiquidityEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "pool_obj",
          "type": "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>"
        },
        {
          "name": "position_object",
          "type": "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>"
        },
        {
          "name": "liquidity_amount",
          "type": "u128"
        },
        {
          "name": "is_unstake",
          "type": "bool"
        }
      ]
    },
    {
      "name": "AddLiquidityInputs",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "position_object",
          "type": "0x1::option::Option<0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>>"
        },
        {
          "name": "token_a_metadata",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_b_metadata",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "tick_lower",
          "type": "0x1::option::Option<u32>"
        },
        {
          "name": "tick_upper",
          "type": "0x1::option::Option<u32>"
        },
        {
          "name": "fee_tier",
          "type": "u8"
        },
        {
          "name": "amount_a_desired",
          "type": "u64"
        },
        {
          "name": "amount_b_desired",
          "type": "u64"
        },
        {
          "name": "amount_a_min",
          "type": "u64"
        },
        {
          "name": "amount_b_min",
          "type": "u64"
        },
        {
          "name": "deadline",
          "type": "u64"
        },
        {
          "name": "is_stake",
          "type": "bool"
        }
      ]
    },
    {
      "name": "AddLiquidityOptimallyEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "pool",
          "type": "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>"
        },
        {
          "name": "position_object",
          "type": "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>"
        },
        {
          "name": "token_a_metadata",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_b_metadata",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "amount_a_in",
          "type": "u64"
        },
        {
          "name": "amount_b_in",
          "type": "u64"
        },
        {
          "name": "amount_a_added",
          "type": "u64"
        },
        {
          "name": "amount_b_added",
          "type": "u64"
        },
        {
          "name": "amount_a_left",
          "type": "u64"
        },
        {
          "name": "amount_b_left",
          "type": "u64"
        },
        {
          "name": "is_stake",
          "type": "bool"
        },
        {
          "name": "loop_count",
          "type": "u64"
        }
      ]
    },
    {
      "name": "AddLiquidityOptimallyInputs",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "position_object",
          "type": "0x1::option::Option<0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>>"
        },
        {
          "name": "token_a_metadata",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_b_metadata",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "tick_lower",
          "type": "0x1::option::Option<u32>"
        },
        {
          "name": "tick_upper",
          "type": "0x1::option::Option<u32>"
        },
        {
          "name": "fee_tier",
          "type": "u8"
        },
        {
          "name": "amount_a_in",
          "type": "u64"
        },
        {
          "name": "amount_b_in",
          "type": "u64"
        },
        {
          "name": "amount_a_min",
          "type": "u64"
        },
        {
          "name": "amount_b_min",
          "type": "u64"
        },
        {
          "name": "deadline",
          "type": "u64"
        },
        {
          "name": "is_stake",
          "type": "bool"
        },
        {
          "name": "dust_threshold",
          "type": "u64"
        }
      ]
    },
    {
      "name": "HyperionAdapterConfig",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "key"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "positions",
          "type": "0x1::ordered_map::OrderedMap<address, vector<0xc9613ed6276f7c70a5eabdef237dc57ea07a72f563d15cd998dc31ebe6cc0db5::hyperion_adapter::Position>>"
        },
        {
          "name": "ltv_map",
          "type": "0x1::ordered_map::OrderedMap<0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>, 0x1::simple_map::SimpleMap<u64, u64>>"
        },
        {
          "name": "reward_tokens",
          "type": "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
        }
      ]
    },
    {
      "name": "LiquidateNonFAPositionEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "credit_account_address",
          "type": "address"
        },
        {
          "name": "removed_assets_metadata",
          "type": "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>"
        }
      ]
    },
    {
      "name": "LiquidateNonFAPositionInputs",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "token_a_min_out",
          "type": "u64"
        },
        {
          "name": "token_b_min_out",
          "type": "u64"
        }
      ]
    },
    {
      "name": "LtvMapSet",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool_obj",
          "type": "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>"
        },
        {
          "name": "ltv_map",
          "type": "0x1::simple_map::SimpleMap<u64, u64>"
        }
      ]
    },
    {
      "name": "RebalanceEvent",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "pool",
          "type": "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::LiquidityPoolV3>"
        },
        {
          "name": "old_position_object",
          "type": "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>"
        },
        {
          "name": "new_position_object",
          "type": "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>"
        },
        {
          "name": "tick_lower",
          "type": "u32"
        },
        {
          "name": "tick_upper",
          "type": "u32"
        }
      ]
    },
    {
      "name": "RebalanceInputs",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "position_object",
          "type": "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>"
        },
        {
          "name": "token_a_metadata",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_b_metadata",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "fee_tier",
          "type": "u8"
        },
        {
          "name": "amount_a_out_min",
          "type": "u64"
        },
        {
          "name": "amount_b_out_min",
          "type": "u64"
        },
        {
          "name": "tick_lower",
          "type": "u32"
        },
        {
          "name": "tick_upper",
          "type": "u32"
        },
        {
          "name": "additional_amount_a",
          "type": "u64"
        },
        {
          "name": "additional_amount_b",
          "type": "u64"
        },
        {
          "name": "min_amount_a",
          "type": "u64"
        },
        {
          "name": "min_amount_b",
          "type": "u64"
        },
        {
          "name": "deadline",
          "type": "u64"
        },
        {
          "name": "is_stake",
          "type": "bool"
        },
        {
          "name": "dust_threshold",
          "type": "u64"
        }
      ]
    },
    {
      "name": "RemoveLiquidityInputs",
      "is_native": false,
      "is_event": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "position_object",
          "type": "0x1::object::Object<0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::position_v3::Info>"
        },
        {
          "name": "liquidity_delta",
          "type": "u128"
        },
        {
          "name": "token_a_metadata",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "token_b_metadata",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        },
        {
          "name": "fee_tier",
          "type": "u8"
        },
        {
          "name": "amount_a_min",
          "type": "u64"
        },
        {
          "name": "amount_b_min",
          "type": "u64"
        },
        {
          "name": "is_unstake",
          "type": "bool"
        }
      ]
    },
    {
      "name": "RewardTokenAdded",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "reward_token",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        }
      ]
    },
    {
      "name": "RewardTokenRemoved",
      "is_native": false,
      "is_event": true,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "reward_token",
          "type": "0x1::object::Object<0x1::fungible_asset::Metadata>"
        }
      ]
    }
  ]
} as const;
