// This file is auto-generated by the generate-abis.ts script
export const thalaV1_stable_pool_scripts_abi = {
  "address": "0x0",
  "name": "stable_pool_scripts",
  "friends": [],
  "exposed_functions": [
    {
      "name": "add_liquidity",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "u64",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "remove_liquidity",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "swap_exact_in",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "swap_exact_out",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "create_stable_pool",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        },
        {
          "constraints": []
        }
      ],
      "params": [
        "&signer",
        "u64",
        "u64",
        "u64",
        "u64",
        "u64"
      ],
      "return": []
    },
    {
      "name": "set_pause_thalaswap",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "bool"
      ],
      "return": []
    }
  ],
  "structs": []
} as const;
