// This file is auto-generated by the generate-abis.ts script
export const thalaV2_staking_abi = {
  "address": "0x0",
  "name": "staking",
  "friends": [],
  "exposed_functions": [
    {
      "name": "apt_pending_withdrawal",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "u64"
      ]
    },
    {
      "name": "burn_from_sthapt",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "address",
        "u64"
      ],
      "return": []
    },
    {
      "name": "burn_from_thapt",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "address",
        "u64"
      ],
      "return": []
    },
    {
      "name": "commission_fee",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "u64"
      ]
    },
    {
      "name": "commission_fee_bps",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "u64"
      ]
    },
    {
      "name": "complete_unstake_APT",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64"
      ],
      "return": [
        "0x1::coin::Coin<0x1::aptos_coin::AptosCoin>"
      ]
    },
    {
      "name": "cumulative_deposit",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "u128"
      ]
    },
    {
      "name": "cumulative_restake",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "u128"
      ]
    },
    {
      "name": "cumulative_rewards",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "u128"
      ]
    },
    {
      "name": "cumulative_withdrawn",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "u128"
      ]
    },
    {
      "name": "extra_rewards_for_sthAPT_holders_bps",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "u64"
      ]
    },
    {
      "name": "extract_commission_fee",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer"
      ],
      "return": [
        "0x1::coin::Coin<0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::ThalaAPT>"
      ]
    },
    {
      "name": "extract_rewards_kept",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer"
      ],
      "return": [
        "0x1::coin::Coin<0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::ThalaAPT>"
      ]
    },
    {
      "name": "freeze_thapt_coin_stores",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "vector<address>"
      ],
      "return": []
    },
    {
      "name": "init_fees_exempt",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer"
      ],
      "return": []
    },
    {
      "name": "init_pause_flag",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer"
      ],
      "return": []
    },
    {
      "name": "init_seed_liquidity",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer"
      ],
      "return": []
    },
    {
      "name": "initialized_pause_flag",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "bool"
      ]
    },
    {
      "name": "next_unstake_request_id",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "u64"
      ]
    },
    {
      "name": "paused",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "bool"
      ]
    },
    {
      "name": "reconcile",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64"
      ],
      "return": []
    },
    {
      "name": "request_unstake_APT",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::coin::Coin<0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::ThalaAPT>"
      ],
      "return": []
    },
    {
      "name": "rewards_kept",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "u64"
      ]
    },
    {
      "name": "set_commission_fee_bps",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64"
      ],
      "return": []
    },
    {
      "name": "set_extra_rewards_for_sthAPT_holders_bps",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64"
      ],
      "return": []
    },
    {
      "name": "set_fees_exempt",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "vector<address>"
      ],
      "return": []
    },
    {
      "name": "set_pause",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "bool"
      ],
      "return": []
    },
    {
      "name": "set_stake_thAPT_fee_bps",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64"
      ],
      "return": []
    },
    {
      "name": "set_unstake_APT_fee_bps",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64"
      ],
      "return": []
    },
    {
      "name": "set_unstake_duration_seconds",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "u64"
      ],
      "return": []
    },
    {
      "name": "stake_APT",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::coin::Coin<0x1::aptos_coin::AptosCoin>"
      ],
      "return": [
        "0x1::coin::Coin<0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::ThalaAPT>"
      ]
    },
    {
      "name": "stake_APT_v2",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "0x1::coin::Coin<0x1::aptos_coin::AptosCoin>"
      ],
      "return": [
        "0x1::coin::Coin<0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::ThalaAPT>"
      ]
    },
    {
      "name": "stake_thAPT",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::coin::Coin<0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::ThalaAPT>"
      ],
      "return": [
        "0x1::coin::Coin<0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::StakedThalaAPT>"
      ]
    },
    {
      "name": "stake_thAPT_fee_bps",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "u64"
      ]
    },
    {
      "name": "stake_thAPT_v2",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "0x1::coin::Coin<0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::ThalaAPT>"
      ],
      "return": [
        "0x1::coin::Coin<0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::StakedThalaAPT>"
      ]
    },
    {
      "name": "sthAPT_reward_rate",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "0x1::fixed_point64::FixedPoint64"
      ]
    },
    {
      "name": "sthAPT_supply",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "u64"
      ]
    },
    {
      "name": "thAPT_staking",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "u64"
      ]
    },
    {
      "name": "thAPT_sthAPT_exchange_rate",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "u64",
        "u64"
      ]
    },
    {
      "name": "thAPT_sthAPT_exchange_rate_synced",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "u64",
        "u64"
      ]
    },
    {
      "name": "thAPT_supply",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "u64"
      ]
    },
    {
      "name": "thAPT_unstaking",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "u64"
      ]
    },
    {
      "name": "total_stake",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "u128"
      ]
    },
    {
      "name": "unfreeze_thapt_coin_stores",
      "visibility": "public",
      "is_entry": true,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "vector<address>"
      ],
      "return": []
    },
    {
      "name": "unstake_APT_fee_bps",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "u64"
      ]
    },
    {
      "name": "unstake_duration_seconds",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [],
      "return": [
        "u64"
      ]
    },
    {
      "name": "unstake_thAPT",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "&signer",
        "0x1::coin::Coin<0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::StakedThalaAPT>"
      ],
      "return": [
        "0x1::coin::Coin<0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::ThalaAPT>"
      ]
    },
    {
      "name": "unstake_thAPT_v2",
      "visibility": "public",
      "is_entry": false,
      "is_view": false,
      "generic_type_params": [],
      "params": [
        "0x1::coin::Coin<0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::StakedThalaAPT>"
      ],
      "return": [
        "0x1::coin::Coin<0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::ThalaAPT>"
      ]
    },
    {
      "name": "user_unstake",
      "visibility": "public",
      "is_entry": false,
      "is_view": true,
      "generic_type_params": [],
      "params": [
        "address"
      ],
      "return": [
        "vector<0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::UnstakeRequest>"
      ]
    }
  ],
  "structs": [
    {
      "name": "CompleteUnstakeAPTEvent",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "request_id",
          "type": "u64"
        },
        {
          "name": "account",
          "type": "address"
        },
        {
          "name": "unstaked_amount",
          "type": "u64"
        },
        {
          "name": "withdrawn_amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "FeesExempt",
      "is_native": false,
      "is_event": false,
      "is_enum": false,
      "abilities": [
        "key"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "addresses",
          "type": "vector<address>"
        }
      ]
    },
    {
      "name": "PauseEvent",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "paused",
          "type": "bool"
        }
      ]
    },
    {
      "name": "PauseFlag",
      "is_native": false,
      "is_event": false,
      "is_enum": false,
      "abilities": [
        "key"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "paused",
          "type": "bool"
        }
      ]
    },
    {
      "name": "RequestUnstakeAPTEvent",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "request_id",
          "type": "u64"
        },
        {
          "name": "account",
          "type": "address"
        },
        {
          "name": "request_amount",
          "type": "u64"
        },
        {
          "name": "actual_amount",
          "type": "u64"
        },
        {
          "name": "fee_amount",
          "type": "u64"
        },
        {
          "name": "active_decrement",
          "type": "u64"
        },
        {
          "name": "pending_inactive_increment",
          "type": "u64"
        },
        {
          "name": "withdrawn_amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "RestakeAPTEvent",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "request_id",
          "type": "u64"
        },
        {
          "name": "account",
          "type": "address"
        },
        {
          "name": "pool",
          "type": "address"
        },
        {
          "name": "restaked_APT",
          "type": "u64"
        },
        {
          "name": "cumulative_restake_increment",
          "type": "u64"
        }
      ]
    },
    {
      "name": "StakeAPTEvent",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "account",
          "type": "address"
        },
        {
          "name": "pool",
          "type": "address"
        },
        {
          "name": "staked_APT",
          "type": "u64"
        },
        {
          "name": "minted_thAPT",
          "type": "u64"
        }
      ]
    },
    {
      "name": "StakeThalaAPTEvent",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "account",
          "type": "address"
        },
        {
          "name": "thAPT_staked",
          "type": "u64"
        },
        {
          "name": "thAPT_fee",
          "type": "u64"
        },
        {
          "name": "sthAPT_minted",
          "type": "u64"
        }
      ]
    },
    {
      "name": "StakedThalaAPT",
      "is_native": false,
      "is_event": false,
      "is_enum": false,
      "abilities": [],
      "generic_type_params": [],
      "fields": [
        {
          "name": "dummy_field",
          "type": "bool"
        }
      ]
    },
    {
      "name": "SyncRewardsEvent",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "total_active",
          "type": "u128"
        },
        {
          "name": "total_inactive",
          "type": "u128"
        },
        {
          "name": "total_pending_inactive",
          "type": "u128"
        },
        {
          "name": "cumulative_restake",
          "type": "u128"
        },
        {
          "name": "cumulative_deposit",
          "type": "u128"
        },
        {
          "name": "cumulative_withdrawn",
          "type": "u128"
        },
        {
          "name": "prev_cumulative_rewards",
          "type": "u128"
        },
        {
          "name": "cumulative_rewards",
          "type": "u128"
        },
        {
          "name": "rewards_amount",
          "type": "u64"
        },
        {
          "name": "rewards_commission",
          "type": "u64"
        },
        {
          "name": "rewards_for_sthAPT_holders",
          "type": "u64"
        },
        {
          "name": "rewards_kept",
          "type": "u64"
        }
      ]
    },
    {
      "name": "TLSD",
      "is_native": false,
      "is_event": false,
      "is_enum": false,
      "abilities": [
        "key"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "cumulative_restake",
          "type": "u128"
        },
        {
          "name": "cumulative_deposit",
          "type": "u128"
        },
        {
          "name": "cumulative_withdrawn",
          "type": "u128"
        },
        {
          "name": "cumulative_rewards",
          "type": "u128"
        },
        {
          "name": "unstake_APT_fee_bps",
          "type": "u64"
        },
        {
          "name": "stake_thAPT_fee_bps",
          "type": "u64"
        },
        {
          "name": "commission_fee_bps",
          "type": "u64"
        },
        {
          "name": "commission_fee",
          "type": "0x1::coin::Coin<0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::ThalaAPT>"
        },
        {
          "name": "extra_rewards_for_sthAPT_holders_bps",
          "type": "u64"
        },
        {
          "name": "rewards_kept",
          "type": "0x1::coin::Coin<0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::ThalaAPT>"
        },
        {
          "name": "thAPT_staking",
          "type": "0x1::coin::Coin<0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::ThalaAPT>"
        },
        {
          "name": "thAPT_unstaking",
          "type": "0x1::coin::Coin<0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::ThalaAPT>"
        },
        {
          "name": "apt_pending_withdrawal",
          "type": "0x1::coin::Coin<0x1::aptos_coin::AptosCoin>"
        },
        {
          "name": "next_unstake_request_id",
          "type": "u64"
        },
        {
          "name": "unstake_duration_seconds",
          "type": "u64"
        },
        {
          "name": "thAPT_burn_capability",
          "type": "0x1::coin::BurnCapability<0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::ThalaAPT>"
        },
        {
          "name": "thAPT_freeze_capability",
          "type": "0x1::coin::FreezeCapability<0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::ThalaAPT>"
        },
        {
          "name": "thAPT_mint_capability",
          "type": "0x1::coin::MintCapability<0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::ThalaAPT>"
        },
        {
          "name": "sthAPT_burn_capability",
          "type": "0x1::coin::BurnCapability<0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::StakedThalaAPT>"
        },
        {
          "name": "sthAPT_freeze_capability",
          "type": "0x1::coin::FreezeCapability<0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::StakedThalaAPT>"
        },
        {
          "name": "sthAPT_mint_capability",
          "type": "0x1::coin::MintCapability<0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::StakedThalaAPT>"
        }
      ]
    },
    {
      "name": "ThalaAPT",
      "is_native": false,
      "is_event": false,
      "is_enum": false,
      "abilities": [],
      "generic_type_params": [],
      "fields": [
        {
          "name": "dummy_field",
          "type": "bool"
        }
      ]
    },
    {
      "name": "UnstakeRequest",
      "is_native": false,
      "is_event": false,
      "is_enum": false,
      "abilities": [
        "copy",
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "account",
          "type": "address"
        },
        {
          "name": "request_id",
          "type": "u64"
        },
        {
          "name": "start_sec",
          "type": "u64"
        },
        {
          "name": "end_sec",
          "type": "u64"
        },
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "UnstakeThalaAPTEvent",
      "is_native": false,
      "is_event": true,
      "is_enum": false,
      "abilities": [
        "drop",
        "store"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "account",
          "type": "address"
        },
        {
          "name": "thAPT_unstaked",
          "type": "u64"
        },
        {
          "name": "sthAPT_burnt",
          "type": "u64"
        }
      ]
    },
    {
      "name": "UserUnstake",
      "is_native": false,
      "is_event": false,
      "is_enum": false,
      "abilities": [
        "key"
      ],
      "generic_type_params": [],
      "fields": [
        {
          "name": "requests",
          "type": "0x1::smart_table::SmartTable<u64, 0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::UnstakeRequest>"
        }
      ]
    }
  ]
} as const;
